@c This is part of the Emacs manual.
@c Copyright (C) 2002 Free Software Foundation, Inc.
@c See file emacs.texi for copying conditions.

@node Antinews, Mac OS, X Resources, Top
@appendix Emacs 21.3 Antinews

  For those users who live backwards in time, here is information about
downgrading to Emacs version 21.3.  We hope you will enjoy the greater
simplicity that results from the absence of many newer features.

@itemize @bullet
@item
The input methods for Emacs are included in a separate distribution
called ``Leim''.  To use them, you must extract the Leim tar file on
top of the Emacs distribution, into the same directory, before you
build Emacs.

@item
The file position and line number information is now at the end
of the mode line.

@item
When a file is managed with version control, the command @kbd{C-x C-q}
(whose general meaning is to make a buffer read-only or writable) now
does so by checking the file in or out.  Checking the file out makes
the buffer writable; checking it in makes the buffer read-only (at
least with RCS).

You can still use @kbd{C-x v v} to do these operations if you wish;
its meaning is unchanged.  If you want to control the buffer's
read-only flag without performing any version control operation,
use @kbd{M-x toggle-read-only}.

@item
Filesets are not supported.

@item
For simplicity, windows always have fringes.  We wouldn't want
to in-fringe anyone's windows.  Likewise, horizontal scrolling
always works the same automatic way.

@item
When you are logged in as root, all files now give you writable
buffers in Emacs reflecting the fact that you can write any files.

@item
Unicode support and unification between Latin-@var{n} character
sets have been removed.  Cutting and pasting X selections does not
support ``extended segments'' so there are certain coding systems
it cannot handle.

@item
@kbd{C-w} in an incremental search always grabs an entire word
into the search string.  More precisely, it grabs text through
the next end of a word.

@item
Yanking now preserves all text properties that were in the killed
text.  The variable @code{yank-excluded-properties} has no meaning.

@item
Occur mode, Info mode, and Comint-derived modes now control
fontification in their own way, and @kbd{M-x font-lock-mode}
has nothing to do with it.  To control fontification in Info
mode, use the variable @code{Info-fontify}.

@item
In Dired's @kbd{!} command, @samp{*} and @samp{?} now
cause substitution of the file names wherever they appear---not
only when they are surrounded by whitespace.

@item
Minibuffer completion commands now always complete the entire
minibuffer contents, just as if you had typed them at the end
of the minibuffer, no matter where point is actually located.

@item
An unquoted @samp{$} in a file name is now an error, if the following
name is not recognized as an environment variable.  Thus,
the file name @file{foo$bar} would probably be an error.  Meanwhile,
the @code{setenv} command does not expand @samp{$} at all.

@item
Commands to set the mark at a place away from point, including
@kbd{M-@@}, @kbd{M-h}, etc., don't do anything special when you repeat
them.  In most cases, typing these commands multiple times is
equivalent to using them once.  @kbd{M-h} does not use its numeric
argument.

@item
@kbd{C-@key{SPC} C-@key{SPC}} has no special meaning and neither does
@kbd{C-u C-x C-x}.

@item
There is no horizontal-bar cursor.

@item
The faces @code{minibuffer-prompt} and @code{mode-line-inactive}
do not exist, and the features they control don't exist either.

@item
The default value of @code{keyboard-coding-system} is always @code{nil}.
Emacs does not set it based on your locale settings.
If you want some other value, you must set it yourself.

@item
SGML mode does not handle XML syntax, and does not have indentation support.

@item
The @kbd{C-h} subcommands have been rearranged--especially those that
display specific files.  Type @kbd{C-h C-h} to see a list of these
commands; that will show you what is different.

@item
Emacs does not read @file{~/.abbrev_defs} automatically; if you want
to load abbrev definitions from a file, you must always do so
explicitly.

@item
The @samp{--fullwidth}, @samp{--fullheight} and @samp{--fullscreen}
command line options are not supported.

@item
The @samp{--geometry} option now entirely applies only to the initial
frame.

@item
Many commands have been removed from the menus or rearranged.

@item
Many @code{etags} features for customizing parsing using regexps
have been removed.

@item
The CUA, ido, table, tramp, reveal, ruler-mode, and ibuffer packages
have been removed.  So has the spreadsheet, SES, and the algebraic
calculator, Calc.  (We distribute Calc separately.)

@item
The kmacro package has been removed.  To start a keyboard macro you
must use @kbd{C-x (}; to end one, @kbd{C-x )}; to execute the last
one, @kbd{C-x e}.

@item
To keep up with decreasing computer memory capacity and disk space, many
other functions and files have been eliminated in Emacs 21.3.
@end itemize

@ignore
   arch-tag: 32932bd9-46f5-41b2-8a0e-fb0cc4caeb29
@end ignore
