# Makefile for leim subdirectory in GNU Emacs on the Microsoft W32 API.
# Copyright (C) 1997 Electrotechnical Laboratory, JAPAN.
# Licensed to the Free Software Foundation.

# This file is part of GNU Emacs.

# GNU Emacs is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2, or (at your option)
# any later version.
#
# GNU Emacs is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with GNU Emacs; see the file COPYING.  If not, write to the
# Free Software Foundation, Inc., 59 Temple Place - Suite 330,
# Boston, MA 02111-1307, USA.

# 
# Sets up the system dependent macros.
#
!include ..\nt\makefile.def

srcdir=.

# Where to install LEIM files.
INSTALLDIR=$(INSTALL_DIR)\leim

# On Xenix and the IBM RS6000, double-dot gets screwed up.
dot = .

# Which Emacs to use to convert TIT files to Emacs Lisp files,
# byte-compile Emacs Lisp files, and generate the file leim-list.el.
BUILT_EMACS = $(dot)$(dot)\src\$(BLD)\emacs.exe

buildlisppath=$(dot)$(dot)/lisp

# How to run Emacs.
RUN_EMACS = $(BUILT_EMACS) -batch --no-init-file --no-site-file --multibyte

# Subdirectories to be made if $(srcdir) is different from the current
# directory.
SUBDIRS=quail

# Files generated from TIT dictionaries for Chinese GB character set.
TIT_GB=\
	quail/CTLau.elc		\
	quail/CCDOSPY.elc	\
	quail/Punct.elc		\
	quail/PY.elc		\
	quail/QJ.elc		\
	quail/SW.elc		\
	quail/TONEPY.elc	\
	quail/ZIRANMA.elc

# Files generated from TIT dictionaries for Chinese BIG5 character set.
TIT_BIG5=\
	quail/4Corner.elc	\
	quail/ARRAY30.elc	\
	quail/CTLauB.elc	\
	quail/ECDICT.elc	\
	quail/ETZY.elc		\
	quail/Punct-b5.elc	\
	quail/PY-b5.elc		\
	quail/QJ-b5.elc		\
	quail/ZOZY.elc

CHINESE_TIT=$(TIT_GB) $(TIT_BIG5)

NON_TIT_GB=$(srcdir)/quail/py-punct.elc

NON_TIT_BIG5=$(srcdir)/quail/quick-b5.elc $(srcdir)/quail/tsang-b5.elc \
	     $(srcdir)/quail/pypunct-b5.elc

NON_TIT_CNS=$(srcdir)/quail/quick-cns.elc $(srcdir)/quail/tsang-cns.elc

CHINESE_NON_TIT=$(NON_TIT_GB) $(NON_TIT_BIG5) $(NON_TIT_CNS)

CHINESE_GB=$(TIT_GB) $(NON_TIT_GB)

CHINESE_BIG5=$(TIT_BIG5) $(NON_TIT_BIG5) 

CHINESE_CNS=$(NON_TIT_CNS) 

JAPANESE=$(srcdir)/quail/japanese.elc $(srcdir)/ja-dic/ja-dic.elc

KOREAN=	$(srcdir)/quail/hangul.elc	\
	$(srcdir)/quail/hangul3.elc	\
	$(srcdir)/quail/hanja.elc	\
	$(srcdir)/quail/hanja-jis.elc	\
	$(srcdir)/quail/symbol-ksc.elc

THAI=$(srcdir)/quail/thai.elc

VIETNAMESE=$(srcdir)/quail/viqr.elc

LAO=$(srcdir)/quail/lao.elc $(srcdir)/quail/lrt.elc

INDIAN=$(srcdir)/quail/devanagari.elc

TIBETAN=$(srcdir)/quail/tibetan.elc

LATIN=$(srcdir)/quail/latin-pre.elc $(srcdir)/quail/latin-post.elc

SLAVIC= \
	$(srcdir)/quail/czech.elc \
	$(srcdir)/quail/slovak.elc

GREEK=$(srcdir)/quail/greek.elc

RUSSIAN=$(srcdir)/quail/cyrillic.elc $(srcdir)/quail/cyril-jis.elc

MISC= \
	$(srcdir)/quail/ethiopic.elc \
	$(srcdir)/quail/ipa.elc \
	$(srcdir)/quail/hebrew.elc

CHINESE=$(CHINESE_GB) $(CHINESE_BIG5) $(CHINESE_CNS)
EASTASIA=$(CHINESE) $(JAPANESE) $(KOREAN)
ASIA=$(EASTASIA) $(THAI) $(VIETNAMESE) $(LAO) $(INDIAN) $(TIBETAN)
EUROPEAN=$(LATIN) $(SLAVIC) $(GREEK) $(RUSSIAN)
WORLD=$(ASIA) $(EUROPEAN) $(MISC)

TIT=$(CHINESE_TIT)
NON_TIT=$(CHINESE_NON_TIT) $(JAPANESE) $(KOREAN) $(EUROPEAN) $(MISC)

all: $(BUILT_EMACS) $(SUBDIRS) $(TIT) leim-list.el

# To ensure that we can run Emacs.  This target is ignored (never
# being hit) if a user changes default value of EMACS.
$(dot)$(dot)/src/emacs:
	cd ../src; $(MAKE) $(MFLAGS) emacs

$(SUBDIRS):
	mkdir $@
	echo stamp>stamp-subdir

# Rule to generate quail/*.el from CXTERM-DIC/*.tit.
$(TIT): $(SUBDIRS)
	set EMACSLOADPATH=$(buildlisppath)
	$(RUN_EMACS) -l $(buildlisppath)/international/titdic-cnv \
	    --eval "(batch-titdic-convert t)" -dir quail $(srcdir)/CXTERM-DIC
	$(RUN_EMACS)  -l $(buildlisppath)/international/quail \
	    -f batch-byte-compile $(TIT)

.SUFFIXES: .elc .el

.el.elc:
	set EMACSLOADPATH=$(buildlisppath)
	$(RUN_EMACS) -f batch-byte-compile $<

leim-list.el: $(SUBDIRS) $(WORLD)
	set EMACSLOADPATH=$(buildlisppath)
	$(RUN_EMACS) -l $(buildlisppath)/international/quail \
	    --eval "(update-leim-list-file \".\")"

install: all
	- mkdir $(INSTALLDIR)
	- $(DEL) same-dir.tst
	- $(DEL) $(INSTALLDIR)\same-dir.tst
	echo SameDirTest > $(INSTALLDIR)\same-dir.tst
	if not exist same-dir.tst $(CP) leim-list.el $(INSTALLDIR)
	if not exist same-dir.tst $(CP_DIR) quail $(INSTALLDIR)\quail
	if not exist same-dir.tst $(CP_DIR) ja-dic $(INSTALLDIR)\ja-dic
	- $(DEL) $(INSTALLDIR)\same-dir.tst

clean mostlyclean:
	for %%f in ($(TIT:/=\)) do $(DEL) %%fc
	for %%f in ($(TIT:/=\)) do $(DEL) %%f
	$(DEL) leim-list.el

distclean maintainer-clean:
	if exist stamp-subdir $(DELTREE) $(SUBDIRS)
	$(DEL) stamp-subdir
