((nil . ((tab-width . 8)
         (sentence-end-double-space . t)
         (fill-column . 70)))
 (c-mode . ((c-file-style . "GNU")
            (c-noise-macro-names . ("UNINIT" "ALIGN_STACK"))))
 (objc-mode . ((c-file-style . "GNU")))
 (log-edit-mode . ((log-edit-font-lock-gnu-style . t)
                   (log-edit-setup-add-author . t)))
 (change-log-mode . ((add-log-time-zone-rule . t)
		     (fill-column . 74)
		     (bug-reference-url-format . "https://debbugs.gnu.org/%s")
		     (mode . bug-reference)))
 (diff-mode . ((mode . whitespace)))
 (emacs-lisp-mode . ((indent-tabs-mode . nil))))
