((nil . ((tab-width . 8)
         (sentence-end-double-space . t)
         (fill-column . 70)
         (projectile-project-configure-cmd . "CFLAGS='-O0 -g3' ./configure --enable-checking='yes,glyphs' --enable-check-lisp-object-type --enable-rust-debug")
         (projectile-project-compilation-cmd . "make -j16")
         (projectile-project-test-cmd . "make check")
         (projectile-project-run-cmd . "./src/remacs")))
 (c-mode . ((c-file-style . "GNU")
            (c-noise-macro-names . ("UNINIT"))))
 (objc-mode . ((c-file-style . "GNU")))
 (log-edit-mode . ((log-edit-font-lock-gnu-style . t)
                   (log-edit-setup-add-author . t)))
 (change-log-mode . ((add-log-time-zone-rule . t)
                     (fill-column . 74)
                     (bug-reference-url-format . "https://debbugs.gnu.org/%s")
                     (mode . bug-reference)))
 (diff-mode . ((mode . whitespace)))
 (emacs-lisp-mode . ((indent-tabs-mode . nil)))
 (rust-mode . ((rust-format-on-save . t)
               (fill-column . 98))))
