;;; quail/cyrillic.el -- Quail package for inputting Cyrillic characters

;; Copyright (C) 1997 Electrotechnical Laboratory, JAPAN.
;; Licensed to the Free Software Foundation.

;; Keywords: multilingual, input method, Cyrillic

;; This file is part of GNU Emacs.

;; GNU Emacs is free software; you can redistribute it and/or modify
;; it under the terms of the GNU General Public License as published by
;; the Free Software Foundation; either version 2, or (at your option)
;; any later version.

;; GNU Emacs is distributed in the hope that it will be useful,
;; but WITHOUT ANY WARRANTY; without even the implied warranty of
;; MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
;; GNU General Public License for more details.

;; You should have received a copy of the GNU General Public License
;; along with GNU Emacs; see the file COPYING.  If not, write to the
;; Free Software Foundation, Inc., 59 Temple Place - Suite 330,
;; Boston, MA 02111-1307, USA.

;;; Code:

(require 'quail)

(quail-define-package
 "cyrillic-jcuken" "Cyrillic" ",L69" nil
 ",L9FC:5= keyboard layout widely used in Russia (ISO 8859-5 encoding)"
 nil t t t t)

;;  1! 2@ 3# 4" 5: 6, 7. 8* 9( 0) -_ =+ ,L!
;;   ,L9  ,LF  ,LC  ,L:  ,L5  ,L=  ,L3  ,LH  ,LI  ,L7  ,LE  ,Lj
;;    ,LD  ,LK  ,L2  ,L0  ,L?  ,L@  ,L>  ,L;  ,L4 ,L6  ,LM
;;     ,LO  ,LG  ,LA  ,L<  ,L8  ,LB  ,LL  ,L1  ,LN  /?

(quail-define-rules
 ("1" ?1)
 ("2" ?2)
 ("3" ?3)
 ("4" ?4)
 ("5" ?5)
 ("6" ?6)
 ("7" ?7)
 ("8" ?8)
 ("9" ?9)
 ("0" ?0)
 ("-" ?-)
 ("=" ?=)
 ("`" ?,Lq)
 ("q" ?,LY)
 ("w" ?,Lf)
 ("e" ?,Lc)
 ("r" ?,LZ)
 ("t" ?,LU)
 ("y" ?,L])
 ("u" ?,LS)
 ("i" ?,Lh)
 ("o" ?,Li)
 ("p" ?,LW)
 ("[" ?,Le)
 ("]" ?,Lj)
 ("a" ?,Ld)
 ("s" ?,Lk)
 ("d" ?,LR)
 ("f" ?,LP)
 ("g" ?,L_)
 ("h" ?,L`)
 ("j" ?,L^)
 ("k" ?,L[)
 ("l" ?,LT)
 (";" ?,LV)
 ("'" ?,Lm)
 ("\\" ?\\)
 ("z" ?,Lo)
 ("x" ?,Lg)
 ("c" ?,La)
 ("v" ?,L\)
 ("b" ?,LX)
 ("n" ?,Lb)
 ("m" ?,Ll)
 ("," ?,LQ)
 ("." ?,Ln)
 ("/" ?/)
 
 ("!" ?!)
 ("@" ?@)
 ("#" ?#)
 ("$" ?\")
 ("%" ?:)
 ("^" ?,)
 ("&" ?.)
 ("*" ?*)
 ("(" ?()
  (")" ?))
 ("_" ?_)
 ("+" ?+)
 ("~" ?,L!)
 ("Q" ?,L9)
 ("W" ?,LF)
 ("E" ?,LC)
 ("R" ?,L:)
 ("T" ?,L5)
 ("Y" ?,L=)
 ("U" ?,L3)
 ("I" ?,LH)
 ("O" ?,LI)
 ("P" ?,L7)
 ("{" ?,LE)
 ("}" ?,LJ)
 ("A" ?,LD)
 ("S" ?,LK)
 ("D" ?,L2)
 ("F" ?,L0)
 ("G" ?,L?)
 ("H" ?,L@)
 ("J" ?,L>)
 ("K" ?,L;)
 ("L" ?,L4)
 (":" ?,L6)
 ("\"" ?,LM)
 ("|" ?|)
 ("Z" ?,LO)
 ("X" ?,LG)
 ("C" ?,LA)
 ("V" ?,L<)
 ("B" ?,L8)
 ("N" ?,LB)
 ("M" ?,LL)
 ("<" ?,L1)
 (">" ?,LN)
 ("?" ??))

;;

(quail-define-package
 "cyrillic-jis-russian" "Cyrillic" "ЖЙ" nil
 "ЙЦУКЕН keyboard layout same as JCUKEN (JIS X0208.1983 encoding)"
		      nil t t t t)

;;  1! 2@ 3# 4" 5: 6, 7. 8* 9( 0) -_ =+ ,L!
;;   ,L9  ,LF  ,LC  ,L:  ,L5  ,L=  ,L3  ,LH  ,LI  ,L7  ,LE  ,Lj
;;    ,LD  ,LK  ,L2  ,L0  ,L?  ,L@  ,L>  ,L;  ,L4  ,L6  ,LM
;;     ,LO  ,LG  ,LA  ,L<  ,L8  ,LB  ,LL  ,L1  ,LN  /?

(quail-define-rules
 ("1" ?１)
 ("2" ?２)
 ("3" ?３)
 ("4" ?４)
 ("5" ?５)
 ("6" ?６)
 ("7" ?７)
 ("8" ?８)
 ("9" ?９)
 ("0" ?０)
 ("-" ?−)
 ("=" ?＝)
 ("`" ?ё)
 ("q" ?й)
 ("w" ?ц)
 ("e" ?у)
 ("r" ?к)
 ("t" ?е)
 ("y" ?н)
 ("u" ?г)
 ("i" ?ш)
 ("o" ?щ)
 ("p" ?з)
 ("[" ?х)
 ("]" ?ъ)
 ("a" ?ф)
 ("s" ?ы)
 ("d" ?в)
 ("f" ?а)
 ("g" ?п)
 ("h" ?р)
 ("j" ?о)
 ("k" ?л)
 ("l" ?д)
 (";" ?ж)
 ("'" ?э)
 ("\\" ?＼)
 ("z" ?я)
 ("x" ?ч)
 ("c" ?с)
 ("v" ?м)
 ("b" ?и)
 ("n" ?т)
 ("m" ?ь)
 ("," ?б)
 ("." ?ю)
 ("/" ?／)
 
 ("!" ?！)
 ("@" ?＠)
 ("#" ?＃)
 ("$" ?”)
 ("%" ?：)
 ("^" ?，)
 ("&" ?．)
 ("*" ?＊)
 ("(" ?（)
  (")" ?）)
 ("_" ?＿)
 ("+" ?＋)
 ("~" ?Ё)
 ("Q" ?Й)
 ("W" ?Ц)
 ("E" ?У)
 ("R" ?К)
 ("T" ?Е)
 ("Y" ?Н)
 ("U" ?Г)
 ("I" ?Ш)
 ("O" ?Щ)
 ("P" ?З)
 ("{" ?Х)
 ("}" ?Ъ)
 ("A" ?Ф)
 ("S" ?Ы)
 ("D" ?В)
 ("F" ?А)
 ("G" ?П)
 ("H" ?Р)
 ("J" ?О)
 ("K" ?Л)
 ("L" ?Д)
 (":" ?Ж)
 ("\"" ?Э)
 ("|" ?｜)
 ("Z" ?Я)
 ("X" ?Ч)
 ("C" ?С)
 ("V" ?М)
 ("B" ?И)
 ("N" ?Т)
 ("M" ?Ь)
 ("<" ?Б)
 (">" ?Ю)
 ("?" ?？))

;;

(quail-define-package
 "cyrillic-macedonian" "Cyrillic" ",L6M" nil
 ",L)*5@B7-,L#, keyboard layout based on JUS.I.K1.004 (ISO 8859-5 encoding)"
 nil t t t t)

;;  1! 2" 3# 4$ 5% 6& 7' 8( 9) 0= /? +* <>
;;   ,L)  ,L*  ,L5  ,L@  ,LB  ,L7  ,LC  ,L8  ,L>  ,L?  ,LH  ,L#
;;    ,L0  ,LA  ,L4  ,LD  ,L3  ,LE  ,L(  ,L:  ,L;  ,LG  ,L,  ,L6
;;     ,L%  ,L/  ,LF  ,L2  ,L1  ,L=  ,L<  ,; .: -_

(quail-define-rules
 ("1" ?1)
 ("2" ?2)
 ("3" ?3)
 ("4" ?4)
 ("5" ?5)
 ("6" ?6)
 ("7" ?7)
 ("8" ?8)
 ("9" ?9)
 ("0" ?0)
 ("-" ?/)
 ("=" ?+)
 ("`" ?<)
 ("q" ?,Ly)
 ("w" ?,Lz)
 ("e" ?,LU)
 ("r" ?,L`)
 ("t" ?,Lb)
 ("y" ?,LW)
 ("u" ?,Lc)
 ("i" ?,LX)
 ("o" ?,L^)
 ("p" ?,L_)
 ("[" ?,Lh)
 ("]" ?,Ls)
 ("a" ?,LP)
 ("s" ?,La)
 ("d" ?,LT)
 ("f" ?,Ld)
 ("g" ?,LS)
 ("h" ?,Le)
 ("j" ?,Lx)
 ("k" ?,LZ)
 ("l" ?,L[)
 (";" ?,Lg)
 ("'" ?,L|)
 ("\\" ?,LV)
 ("z" ?,Lu)
 ("x" ?,L)
 ("c" ?,Lf)
 ("v" ?,LR)
 ("b" ?,LQ)
 ("n" ?,L])
 ("m" ?,L\)
 ("," ?,)
 ("." ?.)
 ("/" ?-)
 
 ("!" ?!)
 ("@" ?\")
 ("#" ?#)
 ("$" ?$)
 ("%" ?%)
 ("^" ?&)
 ("&" ?')
 ("*" ?\()
 ("(" ?\))
 (")" ?=)
 ("_" ??)
 ("+" ?*)
 ("~" ?>)
 ("Q" ?,L))
 ("W" ?,L*)
 ("E" ?,L5)
 ("R" ?,L@)
 ("T" ?,LB)
 ("Y" ?,L7)
 ("U" ?,LC)
 ("I" ?,L8)
 ("O" ?,L>)
 ("P" ?,L?)
 ("{" ?,LH)
 ("}" ?,L#)
 ("A" ?,L0)
 ("S" ?,LA)
 ("D" ?,L4)
 ("F" ?,LD)
 ("G" ?,L3)
 ("H" ?,LE)
 ("J" ?,L()
 ("K" ?,L:)
 ("L" ?,L;)
 (":" ?,LG)
 ("\"" ?,L,)
 ("|" ?,L6)
 ("Z" ?,L%)
 ("X" ?,L/)
 ("C" ?,LF)
 ("V" ?,L2)
 ("B" ?,L1)
 ("N" ?,L=)
 ("M" ?,L<)
 ("<" ?\;)
 (">" ?:)
 ("?" ?_))

;;

(quail-define-package
 "cyrillic-serbian" "Cyrillic" ",L6S" nil
 ",L)*5@B7-,L"+ keyboard layout based on JUS.I.K1.005 (ISO 8859-5 encoding)"
		      nil t t t t)

;;  1! 2" 3# 4$ 5% 6& 7' 8( 9) 0= /? +* <>
;;   ,L)  ,L*  ,L5  ,L@  ,LB  ,L7  ,LC  ,L8  ,L>  ,L?  ,LH  ,L"
;;    ,L0  ,LA  ,L4  ,LD  ,L3  ,LE  ,L(  ,L:  ,L;  ,LG  ,L+  ,L6
;;     ,L%  ,L/  ,LF  ,L2  ,L1  ,L=  ,L<  ,; .: -_

(quail-define-rules
 ("1" ?1)
 ("2" ?2)
 ("3" ?3)
 ("4" ?4)
 ("5" ?5)
 ("6" ?6)
 ("7" ?7)
 ("8" ?8)
 ("9" ?9)
 ("0" ?0)
 ("-" ?/)
 ("=" ?+)
 ("`" ?<)
 ("q" ?,Ly)
 ("w" ?,Lz)
 ("e" ?,LU)
 ("r" ?,L`)
 ("t" ?,Lb)
 ("y" ?,LW)
 ("u" ?,Lc)
 ("i" ?,LX)
 ("o" ?,L^)
 ("p" ?,L_)
 ("[" ?,Lh)
 ("]" ?,Lr)
 ("a" ?,LP)
 ("s" ?,La)
 ("d" ?,LT)
 ("f" ?,Ld)
 ("g" ?,LS)
 ("h" ?,Le)
 ("j" ?,Lx)
 ("k" ?,LZ)
 ("l" ?,L[)
 (";" ?,Lg)
 ("'" ?,L{)
 ("\\" ?,LV)
 ("z" ?,Lu)
 ("x" ?,L)
 ("c" ?,Lf)
 ("v" ?,LR)
 ("b" ?,LQ)
 ("n" ?,L])
 ("m" ?,L\)
 ("," ?,)
 ("." ?.)
 ("/" ?-)
 
 ("!" ?!)
 ("@" ?\")
 ("#" ?#)
 ("$" ?$)
 ("%" ?%)
 ("^" ?&)
 ("&" ?')
 ("*" ?\()
 ("(" ?\))
 (")" ?=)
 ("_" ??)
 ("+" ?*)
 ("~" ?>)
 ("Q" ?,L))
 ("W" ?,L*)
 ("E" ?,L5)
 ("R" ?,L@)
 ("T" ?,LB)
 ("Y" ?,L7)
 ("U" ?,LC)
 ("I" ?,L8)
 ("O" ?,L>)
 ("P" ?,L?)
 ("{" ?,LH)
 ("}" ?,L")
 ("A" ?,L0)
 ("S" ?,LA)
 ("D" ?,L4)
 ("F" ?,LD)
 ("G" ?,L3)
 ("H" ?,LE)
 ("J" ?,L()
 ("K" ?,L:)
 ("L" ?,L;)
 (":" ?,LG)
 ("\"" ?,L+)
 ("|" ?,L6)
 ("Z" ?,L%)
 ("X" ?,L/)
 ("C" ?,LF)
 ("V" ?,L2)
 ("B" ?,L1)
 ("N" ?,L=)
 ("M" ?,L<)
 ("<" ?\;)
 (">" ?:)
 ("?" ?_))

;;

(quail-define-package
 "cyrillic-beylorussian" "Cyrillic" ",L6B" nil
 ",L)*5@B7-,L&. BEYLORUSSIAN (ISO 8859-5 encoding)"
 nil t t t t)

;;  1! 2" 3# 4$ 5% 6& 7' 8( 9) 0= /? +* <>
;;   ,L)  ,L*  ,L5  ,L@  ,LB  ,L7  ,LC  ,L8  ,L>  ,L?  ,LH  ,L&
;;    ,L0  ,LA  ,L4  ,LD  ,L3  ,LE  ,L(  ,L:  ,L;  ,LG  ,L.  ,L6
;;     ,L%  ,L/  ,LF  ,L2  ,L1  ,L=  ,L<  ,; .: -_

(quail-define-rules
 ("1" ?1)
 ("2" ?2)
 ("3" ?3)
 ("4" ?4)
 ("5" ?5)
 ("6" ?6)
 ("7" ?7)
 ("8" ?8)
 ("9" ?9)
 ("0" ?0)
 ("-" ?/)
 ("=" ?+)
 ("`" ?<)
 ("q" ?,Ly)
 ("w" ?,Lz)
 ("e" ?,LU)
 ("r" ?,L`)
 ("t" ?,Lb)
 ("y" ?,LW)
 ("u" ?,Lc)
 ("i" ?,LX)
 ("o" ?,L^)
 ("p" ?,L_)
 ("[" ?,Lh)
 ("]" ?,Lv)
 ("a" ?,LP)
 ("s" ?,La)
 ("d" ?,LT)
 ("f" ?,Ld)
 ("g" ?,LS)
 ("h" ?,Le)
 ("j" ?,Lx)
 ("k" ?,LZ)
 ("l" ?,L[)
 (";" ?,Lg)
 ("'" ?,L~)
 ("\\" ?,LV)
 ("z" ?,Lu)
 ("x" ?,L)
 ("c" ?,Lf)
 ("v" ?,LR)
 ("b" ?,LQ)
 ("n" ?,L])
 ("m" ?,L\)
 ("," ?,)
 ("." ?.)
 ("/" ?-)
 
 ("!" ?!)
 ("@" ?\")
 ("#" ?#)
 ("$" ?$)
 ("%" ?%)
 ("^" ?&)
 ("&" ?')
 ("*" ?\()
 ("(" ?\))
 (")" ?=)
 ("_" ??)
 ("+" ?*)
 ("~" ?>)
 ("Q" ?,L))
 ("W" ?,L*)
 ("E" ?,L5)
 ("R" ?,L@)
 ("T" ?,LB)
 ("Y" ?,L7)
 ("U" ?,LC)
 ("I" ?,L8)
 ("O" ?,L>)
 ("P" ?,L?)
 ("{" ?,LH)
 ("}" ?,L&)
 ("A" ?,L0)
 ("S" ?,LA)
 ("D" ?,L4)
 ("F" ?,LD)
 ("G" ?,L3)
 ("H" ?,LE)
 ("J" ?,L()
 ("K" ?,L:)
 ("L" ?,L;)
 (":" ?,LG)
 ("\"" ?,L.)
 ("|" ?,L6)
 ("Z" ?,L%)
 ("X" ?,L/)
 ("C" ?,LF)
 ("V" ?,L2)
 ("B" ?,L1)
 ("N" ?,L=)
 ("M" ?,L<)
 ("<" ?\;)
 (">" ?:)
 ("?" ?_))

;;

(quail-define-package 
 "cyrillic-ukrainian" "Cyrillic" ",L6U" nil
 ",L$'5@B7-,L&. UKRAINIAN (ISO 8859-5 encoding)

Sorry, but 'ghe with upturn' is not included in ISO 8859-5"
 nil t t t t)

;;  1! 2" 3# 4$ 5% 6& 7' 8( 9) 0= /? +* <>
;;   ,L$  ,L'  ,L5  ,L@  ,LB  ,L7  ,LC  ,L8  ,L>  ,L?  ,LH  ,L&
;;    ,L0  ,LA  ,L4  ,LD  ,L3  ,LE  ,L(  ,L:  ,L;  ,LG  ,L.  ,L6
;;     ,L%  ,L/  ,LF  ,L2  ,L1  ,L=  ,L<  ,; .: -_

(quail-define-rules
 ("1" ?1)
 ("2" ?2)
 ("3" ?3)
 ("4" ?4)
 ("5" ?5)
 ("6" ?6)
 ("7" ?7)
 ("8" ?8)
 ("9" ?9)
 ("0" ?0)
 ("-" ?/)
 ("=" ?+)
 ("`" ?<)
 ("q" ?,Lt)
 ("w" ?,Lw)
 ("e" ?,LU)
 ("r" ?,L`)
 ("t" ?,Lb)
 ("y" ?,LW)
 ("u" ?,Lc)
 ("i" ?,LX)
 ("o" ?,L^)
 ("p" ?,L_)
 ("[" ?,Lh)
 ("]" ?,Lv)
 ("a" ?,LP)
 ("s" ?,La)
 ("d" ?,LT)
 ("f" ?,Ld)
 ("g" ?,LS)
 ("h" ?,Le)
 ("j" ?,Lx)
 ("k" ?,LZ)
 ("l" ?,L[)
 (";" ?,Lg)
 ("'" ?,L~)
 ("\\" ?,LV)
 ("z" ?,Lu)
 ("x" ?,L)
 ("c" ?,Lf)
 ("v" ?,LR)
 ("b" ?,LQ)
 ("n" ?,L])
 ("m" ?,L\)
 ("," ?,)
 ("." ?.)
 ("/" ?-)
 
 ("!" ?!)
 ("@" ?\")
 ("#" ?#)
 ("$" ?$)
 ("%" ?%)
 ("^" ?&)
 ("&" ?')
 ("*" ?\()
 ("(" ?\))
 (")" ?=)
 ("_" ??)
 ("+" ?*)
 ("~" ?>)
 ("Q" ?,L$)
 ("W" ?,L')
 ("E" ?,L5)
 ("R" ?,L@)
 ("T" ?,LB)
 ("Y" ?,L7)
 ("U" ?,LC)
 ("I" ?,L8)
 ("O" ?,L>)
 ("P" ?,L?)
 ("{" ?,LH)
 ("}" ?,L&)
 ("A" ?,L0)
 ("S" ?,LA)
 ("D" ?,L4)
 ("F" ?,LD)
 ("G" ?,L3)
 ("H" ?,LE)
 ("J" ?,L()
 ("K" ?,L:)
 ("L" ?,L;)
 (":" ?,LG)
 ("\"" ?,L.)
 ("|" ?,L6)
 ("Z" ?,L%)
 ("X" ?,L/)
 ("C" ?,LF)
 ("V" ?,L2)
 ("B" ?,L1)
 ("N" ?,L=)
 ("M" ?,L<)
 ("<" ?\;)
 (">" ?:)
 ("?" ?_))

;;

(quail-define-package 
 "cyrillic-yawerty" "Cyrillic" ",L6O" nil
 ",LO25@BK Roman transcription (ISO 8859-5 encoding)

This layout is based on Roman transcription.
When preceded by a '/', the second and the third rows (number key row) change
as follows.

  keytop | Q  W  E  R  T  Y  U  I  O  P  A  S  D
 --------+---------------------------------------
  input  | ,L"  ,L#  ,L$  ,L%  ,L&  ,L'  ,L(  ,L)  ,L*  ,L+  ,L,  ,L.  ,L/"
		      nil t t t t)

;;  1! 2,Lq 3,Lj 4,L! 5% 6^ 7& 8* 9( 0) -_ ,LG  ,LN
;;   ,LO  ,L2  ,L5  ,L@  ,LB  ,LK  ,LC  ,L8  ,L>  ,L?  ,LH  ,LI
;;    ,L0  ,LA  ,L4  ,LD  ,L3  ,LE  ,L9  ,L:  ,L;  ;: '" ,LM
;;     ,L7  ,LL  ,LF  ,L6  ,L1  ,L=  ,L<  ,< .> /?

;;  1! 2,Lq 3,Lj 4,L! 5% 6^ 7& 8* 9( 0) -_ ,LG  ,LN
;;   ,L"  ,L#  ,L$  ,L%  ,L&  ,L'  ,L(  ,L)  ,L*  ,L+  ,LH  ,LI
;;    ,L,  ,L.  ,L/  ,LD  ,L3  ,LE  ,L9  ,L:  ,L;  ;: '" ,LM
;;     ,L7  ,LL  ,LF  ,L6  ,L1  ,L=  ,L<  ,< .> /?

(quail-define-rules
 ("1" ?1)
 ("2" ?2)
 ("3" ?3)
 ("4" ?4)
 ("5" ?5)
 ("6" ?6)
 ("7" ?7)
 ("8" ?8)
 ("9" ?9)
 ("0" ?0)
 ("-" ?-)
 ("=" ?,Lg)
 ("`" ?,Ln)
 ("q" ?,Lo)
 ("w" ?,LR)
 ("e" ?,LU)
 ("r" ?,L`)
 ("t" ?,Lb)
 ("y" ?,Lk)
 ("u" ?,Lc)
 ("i" ?,LX)
 ("o" ?,L^)
 ("p" ?,L_)
 ("[" ?,Lh)
 ("]" ?,Li)
 ("a" ?,LP)
 ("s" ?,La)
 ("d" ?,LT)
 ("f" ?,Ld)
 ("g" ?,LS)
 ("h" ?,Le)
 ("j" ?,LY)
 ("k" ?,LZ)
 ("l" ?,L[)
 (";" ?\;)
 ("'" ?')
 ("\\" ?,Lm)
 ("z" ?,LW)
 ("x" ?,Ll)
 ("c" ?,Lf)
 ("v" ?,LV)
 ("b" ?,LQ)
 ("n" ?,L])
 ("m" ?,L\)
 ("," ?,)
 ("." ?.)
 ("/" ?/)
 
 ("!" ?!)
 ("@" ?,Lq)
 ("#" ?,Lj)
 ("$" ?,L!)
 ("%" ?%)
 ("^" ?^)
 ("&" ?&)
 ("*" ?*)
 ("(" ?\()
 (")" ?\))
 ("_" ?_)
 ("+" ?,LG)
 ("~" ?,LN)
 ("Q" ?,LO)
 ("W" ?,L2)
 ("E" ?,L5)
 ("R" ?,L@)
 ("T" ?,LB)
 ("Y" ?,LK)
 ("U" ?,LC)
 ("I" ?,L8)
 ("O" ?,L>)
 ("P" ?,L?)
 ("{" ?,LH)
 ("}" ?,LI)
 ("A" ?,L0)
 ("S" ?,LA)
 ("D" ?,L4)
 ("F" ?,LD)
 ("G" ?,L3)
 ("H" ?,LE)
 ("J" ?,L9)
 ("K" ?,L:)
 ("L" ?,L;)
 (":" ?:)
 ("\"" ?\")
 ("|" ?,LM)
 ("Z" ?,L7)
 ("X" ?,LL)
 ("C" ?,LF)
 ("V" ?,L6)
 ("B" ?,L1)
 ("N" ?,L=)
 ("M" ?,L<)
 ("<" ?<)
 (">" ?>)
 ("?" ??)
 
 ("/q" ?,Lr)
 ("/w" ?,Ls)
 ("/e" ?,Lt)
 ("/r" ?,Lu)
 ("/t" ?,Lv)
 ("/y" ?,Lw)
 ("/u" ?,Lx)
 ("/i" ?,Ly)
 ("/o" ?,Lz)
 ("/p" ?,L{)
 ("/a" ?,L|)
 ("/s" ?,L~)
 ("/d" ?,L)
 
 ("/Q" ?,L")
 ("/W" ?,L#)
 ("/E" ?,L$)
 ("/R" ?,L%)
 ("/T" ?,L&)
 ("/Y" ?,L')
 ("/U" ?,L()
 ("/I" ?,L))
 ("/O" ?,L*)
 ("/P" ?,L+)
 ("/A" ?,L,)
 ("/S" ?,L.)
 ("/D" ?,L/))
