;;; ethiopic.el --- Quail package for inputting Ethiopic characters  -*-coding: utf-8-emacs;-*-

;; Copyright (C) 1997, 1998, 1999, 2000, 2001, 2002, 2003, 2004, 2005,
;;   2006, 2007, 2008, 2009, 2010, 2011
;;   National Institute of Advanced Industrial Science and Technology (AIST)
;;   Registration Number H14PRO021

;; Keywords: multilingual, input method, ethiopic

;; This file is part of GNU Emacs.

;; GNU Emacs is free software: you can redistribute it and/or modify
;; it under the terms of the GNU General Public License as published by
;; the Free Software Foundation, either version 3 of the License, or
;; (at your option) any later version.

;; GNU Emacs is distributed in the hope that it will be useful,
;; but WITHOUT ANY WARRANTY; without even the implied warranty of
;; MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
;; GNU General Public License for more details.

;; You should have received a copy of the GNU General Public License
;; along with GNU Emacs.  If not, see <http://www.gnu.org/licenses/>.

;; Author: TAKAHASHI Naoto <ntakahas@etl.go.jp>

;;; Commentary:

;;; Code:

(require 'quail)
(require 'ethio-util)

;;
;; The package "ethiopic"
;;

(quail-define-package
 "ethiopic" "Ethiopic"
 '("áŠá‹°áˆ "
   (ethio-prefer-ascii-space "_" "á¡")
   "á¢")
 t "  Quail package for Ethiopic (Tigrigna and Amharic)

When you are in Ethiopic language environment, the following special
keys are available.

C-F9 or `M-x ethio-toggle-space'
  Toggles space characters for keyboard input.  The current mode is
  indicated in mode-line, whether by `_' (ASCII space) or `á¡'
  (Ethiopic colon-like word separator).  Even in the `á¡' mode, an
  ASCII space is inserted if the point is preceded by `an Ethiopic
  punctuation followed by zero or more ASCII spaces'.

S-F5 or `M-x ethio-toggle-punctuation'
  Toggles ASCII punctuation and Ethiopic punctuation for keyboard input.
  The current mode is indicated by `.' (ASCII) or `á¢' (Ethiopic).

S-SPC or `M-x ethio-insert-ethio-space'
  Always insert an Ethiopic word separator `á¡'.  With a prefix number,
  insert that many word separators.

C-' or `M-x ethio-gemination'
  Compose the character before the point with the Ethiopic gemination mark.
  If the character is already composed, decompose it and remove the
  gemination mark."

 ;; The following keys should work as defined in lisp/language/ethio-util,
 ;; even during the translation.
 '(([C-f9]  . quail-execute-non-quail-command)
   ([S-f5]  . quail-execute-non-quail-command)
   (" "     . quail-execute-non-quail-command)
   ([?\S- ] . quail-execute-non-quail-command)
   ([?\C-'] . quail-execute-non-quail-command))
 t t)

(quail-define-rules
 ("he" ?áˆ€)
 ("hu" ?áˆ)
 ("hi" ?áˆ‚)
 ("ha" ?áˆƒ)
 ("hE" ?áˆ„)
 ("hee" ?áˆ„)
 ("h" ?áˆ…)
 ("ho" ?áˆ†)
 ("hW" ?áŠ‹)
 ("hWa" ?áŠ‹)
 ("hWe" ?áŠˆ)
 ("hWu" ?áŠ)
 ("hWi" ?áŠŠ)
 ("hWE" ?áŠŒ)
 ("hW'" ?áŠ)

 ("le" ?áˆˆ)
 ("lu" ?áˆ‰)
 ("li" ?áˆŠ)
 ("la" ?áˆ‹)
 ("lE" ?áˆŒ)
 ("lee" ?áˆŒ)
 ("l" ?áˆ)
 ("lo" ?áˆŽ)
 ("lW" ?áˆ)
 ("lWa" ?áˆ)
 ("lWe" ["áˆö ‡…"])
 ("lWu" ["áˆö ‡‰"])
 ("lWi" ["áˆö ‡†"])
 ("lWE" ["áˆö ‡ˆ"])
 ("lW'" ["áˆö ‡‰"])

 ("Le" ?áˆˆ)
 ("Lu" ?áˆ‰)
 ("Li" ?áˆŠ)
 ("La" ?áˆ‹)
 ("LE" ?áˆŒ)
 ("Lee" ?áˆŒ)
 ("L" ?áˆ)
 ("Lo" ?áˆŽ)
 ("LW" ?áˆ)
 ("LWa" ?áˆ)
 ("LWe" ["áˆö ‡…"])
 ("LWu" ["áˆö ‡‰"])
 ("LWi" ["áˆö ‡†"])
 ("LWE" ["áˆö ‡ˆ"])
 ("LW'" ["áˆö ‡‰"])

 ("He" ?áˆ)
 ("Hu" ?áˆ‘)
 ("Hi" ?áˆ’)
 ("Ha" ?áˆ“)
 ("HE" ?áˆ”)
 ("Hee" ?áˆ”)
 ("H" ?áˆ•)
 ("Ho" ?áˆ–)
 ("HW" ?áˆ—)
 ("HWa" ?áˆ—)
 ("HWe" ["áˆ•ö ‡…"])
 ("HWu" ["áˆ•ö ‡‰"])
 ("HWi" ["áˆ•ö ‡†"])
 ("HWE" ["áˆ•ö ‡ˆ"])
 ("HW'" ["áˆ•ö ‡‰"])

 ("me" ?áˆ˜)
 ("mu" ?áˆ™)
 ("mi" ?áˆš)
 ("ma" ?áˆ›)
 ("mE" ?áˆœ)
 ("mee" ?áˆœ)
 ("m" ?áˆ)
 ("mo" ?áˆž)
 ("mWe" ?ö †ˆ)
 ("mWu" ?ö †¸)
 ("mWi" ?ö †˜)
 ("mW" ?áˆŸ)
 ("mWa" ?áˆŸ)
 ("mWE" ?ö †¨)
 ("mWee" ?ö †¨)
 ("mW'" ?ö †¸)
 ("mY" ?á˜)
 ("mYa" ?á˜)

 ("Me" ?áˆ˜)
 ("Mu" ?áˆ™)
 ("Mi" ?áˆš)
 ("Ma" ?áˆ›)
 ("ME" ?áˆœ)
 ("Mee" ?áˆœ)
 ("M" ?áˆ)
 ("Mo" ?áˆž)
 ("MWe" ?ö †ˆ)
 ("MWu" ?ö †¸)
 ("MWi" ?ö †˜)
 ("MW" ?áˆŸ)
 ("MWa" ?áˆŸ)
 ("MWE" ?ö †¨)
 ("MWee" ?ö †¨)
 ("MW'" ?ö †¸)
 ("MY" ?á˜)
 ("MYa" ?á˜)

 ("`se" ?áˆ )
 ("`su" ?áˆ¡)
 ("`si" ?áˆ¢)
 ("`sa" ?áˆ£)
 ("`sE" ?áˆ¤)
 ("`see" ?áˆ¤)
 ("`s" ?áˆ¥)
 ("`so" ?áˆ¦)
 ("`sW" ?áˆ§)
 ("`sWa" ?áˆ§)
 ("`sWe" ["áˆ¥ö ‡…"])
 ("`sWu" ["áˆ¥ö ‡‰"])
 ("`sWi" ["áˆ¥ö ‡†"])
 ("`sWE" ["áˆ¥ö ‡ˆ"])
 ("`sWee" ["áˆ¥ö ‡ˆ"])
 ("`sW'" ["áˆ¥ö ‡‰"])

 ("s2e" ?áˆ )
 ("s2u" ?áˆ¡)
 ("s2i" ?áˆ¢)
 ("s2a" ?áˆ£)
 ("s2E" ?áˆ¤)
 ("s2ee" ?áˆ¤)
 ("s2" ?áˆ¥)
 ("s2o" ?áˆ¦)
 ("s2W" ?áˆ§)
 ("s2Wa" ?áˆ§)
 ("s2We" ["áˆ¥ö ‡…"])
 ("s2Wu" ["áˆ¥ö ‡‰"])
 ("s2Wi" ["áˆ¥ö ‡†"])
 ("s2WE" ["áˆ¥ö ‡ˆ"])
 ("s2Wee" ["áˆ¥ö ‡ˆ"])
 ("s2W'" ["áˆ¥ö ‡‰"])

 ("sse" ?áˆ )
 ("ssu" ?áˆ¡)
 ("ssi" ?áˆ¢)
 ("ssa" ?áˆ£)
 ("ssE" ?áˆ¤)
 ("ssee" ?áˆ¤)
 ("ss" ?áˆ¥)
 ("sso" ?áˆ¦)
 ("ssW" ?áˆ§)
 ("ssWa" ?áˆ§)
 ("ssWe" ["áˆ¥ö ‡…"])
 ("ssWu" ["áˆ¥ö ‡‰"])
 ("ssWi" ["áˆ¥ö ‡†"])
 ("ssWE" ["áˆ¥ö ‡ˆ"])
 ("ssWee" ["áˆ¥ö ‡ˆ"])
 ("ssW'" ["áˆ¥ö ‡‰"])

 ("re" ?áˆ¨)
 ("ru" ?áˆ©)
 ("ri" ?áˆª)
 ("ra" ?áˆ«)
 ("rE" ?áˆ¬)
 ("ree" ?áˆ¬)
 ("r" ?áˆ­)
 ("ro" ?áˆ®)
 ("rW" ?áˆ¯)
 ("rWa" ?áˆ¯)
 ("rY" ?á™)
 ("rYa" ?á™)
 ("rWe" ["áˆ­ö ‡…"])
 ("rWu" ["áˆ­ö ‡‰"])
 ("rWi" ["áˆ­ö ‡†"])
 ("rWE" ["áˆ­ö ‡ˆ"])
 ("rWee" ["áˆ­ö ‡ˆ"])
 ("rW'" ["áˆ­ö ‡‰"])

 ("Re" ?áˆ¨)
 ("Ru" ?áˆ©)
 ("Ri" ?áˆª)
 ("Ra" ?áˆ«)
 ("RE" ?áˆ¬)
 ("Ree" ?áˆ¬)
 ("R" ?áˆ­)
 ("Ro" ?áˆ®)
 ("RW" ?áˆ¯)
 ("RWa" ?áˆ¯)
 ("RYa" ?á™)
 ("RWe" ["áˆ­ö ‡…"])
 ("RWu" ["áˆ­ö ‡‰"])
 ("RWi" ["áˆ­ö ‡†"])
 ("RWE" ["áˆ­ö ‡ˆ"])
 ("RWee" ["áˆ­ö ‡ˆ"])
 ("RW'" ["áˆ­ö ‡‰"])

 ("se" ?áˆ°)
 ("su" ?áˆ±)
 ("si" ?áˆ²)
 ("sa" ?áˆ³)
 ("sE" ?áˆ´)
 ("see" ?áˆ´)
 ("s" ?áˆµ)
 ("so" ?áˆ¶)
 ("sW" ?áˆ·)
 ("sWa" ?áˆ·)
 ("sWe" ["áˆµö ‡…"])
 ("sWu" ["áˆµö ‡‰"])
 ("sWi" ["áˆµö ‡†"])
 ("sWE" ["áˆµö ‡ˆ"])
 ("sWee" ["áˆµö ‡ˆ"])
 ("sW'" ["áˆµö ‡‰"])

 ("xe" ?áˆ¸)
 ("xu" ?áˆ¹)
 ("xi" ?áˆº)
 ("xa" ?áˆ»)
 ("xE" ?áˆ¼)
 ("xee" ?áˆ¼)
 ("x" ?áˆ½)
 ("xo" ?áˆ¾)
 ("xW" ?áˆ¿)
 ("xWa" ?áˆ¿)
 ("xWe" ["áˆ½ö ‡…"])
 ("xWu" ["áˆ½ö ‡‰"])
 ("xWi" ["áˆ½ö ‡†"])
 ("xWE" ["áˆ½ö ‡ˆ"])
 ("xWee" ["áˆ½ö ‡ˆ"])
 ("xW'" ["áˆ½ö ‡‰"])

 ("qe" ?á‰€)
 ("qu" ?á‰)
 ("qi" ?á‰‚)
 ("qa" ?á‰ƒ)
 ("qE" ?á‰„)
 ("qee" ?á‰„)
 ("q" ?á‰…)
 ("qo" ?á‰†)
 ("qWe" ?á‰ˆ)
 ("qWu" ?á‰)
 ("qWi" ?á‰Š)
 ("qW" ?á‰‹)
 ("qWa" ?á‰‹)
 ("qWE" ?á‰Œ)
 ("qWee" ?á‰Œ)
 ("qW'" ?á‰)

 ("`qe" ?ö †€)
 ("`qu" ?ö †)
 ("`qi" ?ö †‚)
 ("`qa" ?ö †ƒ)
 ("`qE" ?ö †„)
 ("`qee" ?ö †„)
 ("`q" ?ö †…)
 ("`qo" ?ö ††)

 ("q2e" ?ö †€)
 ("q2u" ?ö †)
 ("q2i" ?ö †‚)
 ("q2a" ?ö †ƒ)
 ("q2E" ?ö †„)
 ("q2ee" ?ö †„)
 ("q2" ?ö †…)
 ("q2o" ?ö ††)

 ("qqe" ?ö †€)
 ("qqu" ?ö †)
 ("qqi" ?ö †‚)
 ("qqa" ?ö †ƒ)
 ("qqE" ?ö †„)
 ("qqee" ?ö †„)
 ("qq" ?ö †…)
 ("qqo" ?ö ††)

 ("Qe" ?á‰)
 ("Qu" ?á‰‘)
 ("Qi" ?á‰’)
 ("Qa" ?á‰“)
 ("QE" ?á‰”)
 ("Qee" ?á‰”)
 ("Q" ?á‰•)
 ("Qo" ?á‰–)
 ("QWe" ?á‰˜)
 ("QWu" ?á‰)
 ("QWi" ?á‰š)
 ("QW" ?á‰›)
 ("QWa" ?á‰›)
 ("QWE" ?á‰œ)
 ("QWee" ?á‰œ)
 ("QW'" ?á‰)

 ("be" ?á‰ )
 ("bu" ?á‰¡)
 ("bi" ?á‰¢)
 ("ba" ?á‰£)
 ("bE" ?á‰¤)
 ("bee" ?á‰¤)
 ("b" ?á‰¥)
 ("bo" ?á‰¦)
 ("bWe" ?ö †‰)
 ("bWu" ?ö †¹)
 ("bWi" ?ö †™)
 ("bW" ?á‰§)
 ("bWa" ?á‰§)
 ("bWE" ?ö †©)
 ("bWee" ?ö †©)
 ("bW'" ?ö †¹)

 ("Be" ?á‰ )
 ("Bu" ?á‰¡)
 ("Bi" ?á‰¢)
 ("Ba" ?á‰£)
 ("BE" ?á‰¤)
 ("Bee" ?á‰¤)
 ("B" ?á‰¥)
 ("Bo" ?á‰¦)
 ("BWe" ?ö †‰)
 ("BWu" ?ö †¹)
 ("BWi" ?ö †™)
 ("BW" ?á‰§)
 ("BWa" ?á‰§)
 ("BWE" ?ö †©)
 ("BWee" ?ö †©)
 ("BW'" ?ö †¹)

 ("ve" ?á‰¨)
 ("vu" ?á‰©)
 ("vi" ?á‰ª)
 ("va" ?á‰«)
 ("vE" ?á‰¬)
 ("vee" ?á‰¬)
 ("v" ?á‰­)
 ("vo" ?á‰®)
 ("vW" ?á‰¯)
 ("vWa" ?á‰¯)
 ("vWe" ["á‰­ö ‡…"])
 ("vWu" ["á‰­ö ‡‰"])
 ("vWi" ["á‰­ö ‡†"])
 ("vWE" ["á‰­ö ‡ˆ"])
 ("vWee" ["á‰­ö ‡ˆ"])
 ("vW'" ["á‰­ö ‡‰"])

 ("Ve" ?á‰¨)
 ("Vu" ?á‰©)
 ("Vi" ?á‰ª)
 ("Va" ?á‰«)
 ("VE" ?á‰¬)
 ("Vee" ?á‰¬)
 ("V" ?á‰­)
 ("Vo" ?á‰®)
 ("VW" ?á‰¯)
 ("VWa" ?á‰¯)
 ("VWe" ["á‰­ö ‡…"])
 ("VWu" ["á‰­ö ‡‰"])
 ("VWi" ["á‰­ö ‡†"])
 ("VWE" ["á‰­ö ‡ˆ"])
 ("VWee" ["á‰­ö ‡ˆ"])
 ("VW'" ["á‰­ö ‡‰"])

 ("te" ?á‰°)
 ("tu" ?á‰±)
 ("ti" ?á‰²)
 ("ta" ?á‰³)
 ("tE" ?á‰´)
 ("tee" ?á‰´)
 ("t" ?á‰µ)
 ("to" ?á‰¶)
 ("tW" ?á‰·)
 ("tWa" ?á‰·)
 ("tWe" ["á‰µö ‡…"])
 ("tWu" ["á‰µö ‡‰"])
 ("tWi" ["á‰µö ‡†"])
 ("tWE" ["á‰µö ‡ˆ"])
 ("tWee" ["á‰µö ‡ˆ"])
 ("tW'" ["á‰µö ‡‰"])

 ("ce" ?á‰¸)
 ("cu" ?á‰¹)
 ("ci" ?á‰º)
 ("ca" ?á‰»)
 ("cE" ?á‰¼)
 ("cee" ?á‰¼)
 ("c" ?á‰½)
 ("co" ?á‰¾)
 ("cW" ?á‰¿)
 ("cWa" ?á‰¿)
 ("cWe" ["á‰½ö ‡…"])
 ("cWu" ["á‰½ö ‡‰"])
 ("cWi" ["á‰½ö ‡†"])
 ("cWE" ["á‰½ö ‡ˆ"])
 ("cWee" ["á‰½ö ‡ˆ"])
 ("cW'" ["á‰½ö ‡‰"])

 ("`he" ?áŠ€)
 ("`hu" ?áŠ)
 ("`hi" ?áŠ‚)
 ("`ha" ?áŠƒ)
 ("`hE" ?áŠ„)
 ("`hee" ?áŠ„)
 ("`h" ?áŠ…)
 ("`ho" ?áŠ†)
 ("`hWe" ?áŠˆ)
 ("`hWu" ?áŠ)
 ("`hWi" ?áŠŠ)
 ("`hW" ?áŠ‹)
 ("`hWa" ?áŠ‹)
 ("`hWE" ?áŠŒ)
 ("`hWee" ?áŠŒ)
 ("`hW'" ?áŠ)

 ("h2e" ?áŠ€)
 ("h2u" ?áŠ)
 ("h2i" ?áŠ‚)
 ("h2a" ?áŠƒ)
 ("h2E" ?áŠ„)
 ("h2ee" ?áŠ„)
 ("h2" ?áŠ…)
 ("h2o" ?áŠ†)
 ("h2We" ?áŠˆ)
 ("h2Wu" ?áŠ)
 ("h2Wi" ?áŠŠ)
 ("h2W" ?áŠ‹)
 ("h2Wa" ?áŠ‹)
 ("h2WE" ?áŠŒ)
 ("h2Wee" ?áŠŒ)
 ("h2W'" ?áŠ)

 ("hhe" ?áŠ€)
 ("hhu" ?áŠ)
 ("hhi" ?áŠ‚)
 ("hha" ?áŠƒ)
 ("hhE" ?áŠ„)
 ("hhee" ?áŠ„)
 ("hh" ?áŠ…)
 ("hho" ?áŠ†)
 ("hhWe" ?áŠˆ)
 ("hhWu" ?áŠ)
 ("hhWi" ?áŠŠ)
 ("hhW" ?áŠ‹)
 ("hhWa" ?áŠ‹)
 ("hhWE" ?áŠŒ)
 ("hhWee" ?áŠŒ)
 ("hhW'" ?áŠ)

 ("ne" ?áŠ)
 ("nu" ?áŠ‘)
 ("ni" ?áŠ’)
 ("na" ?áŠ“)
 ("nE" ?áŠ”)
 ("nee" ?áŠ”)
 ("n" ?áŠ•)
 ("no" ?áŠ–)
 ("nW" ?áŠ—)
 ("nWa" ?áŠ—)
 ("nWe" ["áŠ•ö ‡…"])
 ("nWu" ["áŠ•ö ‡‰"])
 ("nWi" ["áŠ•ö ‡†"])
 ("nWE" ["áŠ•ö ‡ˆ"])
 ("nWee" ["áŠ•ö ‡ˆ"])
 ("nW'" ["áŠ•ö ‡‰"])

 ("Ne" ?áŠ˜)
 ("Nu" ?áŠ™)
 ("Ni" ?áŠš)
 ("Na" ?áŠ›)
 ("NE" ?áŠœ)
 ("Nee" ?áŠœ)
 ("N" ?áŠ)
 ("No" ?áŠž)
 ("NW" ?áŠŸ)
 ("NWa" ?áŠŸ)
 ("NWe" ["áŠö ‡…"])
 ("NWu" ["áŠö ‡‰"])
 ("NWi" ["áŠö ‡†"])
 ("NWE" ["áŠö ‡ˆ"])
 ("NWee" ["áŠö ‡ˆ"])
 ("NW'" ["áŠö ‡‰"])

 ; ("e" ?áŠ ) ; old style
 ("u" ?áŠ¡)
 ("U" ?áŠ¡)
 ("i" ?áŠ¢)
 ("a" ?áŠ£)
 ("A" ?áŠ£)
 ("E" ?áŠ¤)
 ; ("ee" ?áŠ¤) ; Alef-E is rare vs Aynu-I, so ee = Aynu-I
 ("I" ?áŠ¥)
 ("e" ?áŠ¥)    ; This is the premise to "new style" for vowels

 ("o" ?áŠ¦)
 ("O" ?áŠ¦)
 ("ea" ?áŠ§)

 ("ke" ?áŠ¨)
 ("ku" ?áŠ©)
 ("ki" ?áŠª)
 ("ka" ?áŠ«)
 ("kE" ?áŠ¬)
 ("kee" ?áŠ¬)
 ("k" ?áŠ­)
 ("ko" ?áŠ®)
 ("kWe" ?áŠ°)
 ("kWu" ?áŠµ)
 ("kWi" ?áŠ²)
 ("kW" ?áŠ³)
 ("kWa" ?áŠ³)
 ("kWE" ?áŠ´)
 ("kWee" ?áŠ´)
 ("kW'" ?áŠµ)

 ("`ke" ?ö †)
 ("`ku" ?ö †‘)
 ("`ki" ?ö †’)
 ("`ka" ?ö †“)
 ("`kE" ?ö †”)
 ("`kee" ?ö †”)
 ("`k" ?ö †•)
 ("`ko" ?ö †–)

 ("k2e" ?ö †)
 ("k2u" ?ö †‘)
 ("k2i" ?ö †’)
 ("k2a" ?ö †“)
 ("k2E" ?ö †”)
 ("k2ee" ?ö †”)
 ("k2" ?ö †•)
 ("k2o" ?ö †–)

 ("kke" ?ö †)
 ("kku" ?ö †‘)
 ("kki" ?ö †’)
 ("kka" ?ö †“)
 ("kkE" ?ö †”)
 ("kkee" ?ö †”)
 ("kk" ?ö †•)
 ("kko" ?ö †–)

 ("Ke" ?áŠ¸)
 ("Ku" ?áŠ¹)
 ("Ki" ?áŠº)
 ("Ka" ?áŠ»)
 ("KE" ?áŠ¼)
 ("Kee" ?áŠ¼)
 ("K" ?áŠ½)
 ("Ko" ?áŠ¾)
 ("KWe" ?á‹€)
 ("KWu" ?á‹…)
 ("KWi" ?á‹‚)
 ("KW" ?á‹ƒ)
 ("KWa" ?á‹ƒ)
 ("KWE" ?á‹„)
 ("KWee" ?á‹„)
 ("KW'" ?á‹…)

 ("Xe" ?ö † )
 ("Xu" ?ö †¡)
 ("Xi" ?ö †¢)
 ("Xa" ?ö †£)
 ("XE" ?ö †¤)
 ("Xee" ?ö †¤)
 ("X" ?ö †¥)
 ("Xo" ?ö †¦)

 ("we" ?á‹ˆ)
 ("wu" ?á‹‰)
 ("wi" ?á‹Š)
 ("wa" ?á‹‹)
 ("wE" ?á‹Œ)
 ("wee" ?á‹Œ)
 ("w" ?á‹)
 ("wo" ?á‹Ž)

 ("`e" ?á‹)
 ("`u" ?á‹‘)
 ("`U" ?á‹‘)
 ("`i" ?á‹’)
 ("`a" ?á‹“)
 ("`A" ?á‹“)
 ("`E" ?á‹”)
 ("`ee" ?á‹”)
 ("`I" ?á‹•)
 ("`o" ?á‹–)
 ("`O" ?á‹–)

 ("e2" ?á‹)
 ("u2" ?á‹‘)
 ("U2" ?á‹‘)
 ("i2" ?á‹’)
 ("a2" ?á‹“)
 ("A2" ?á‹“)
 ("E2" ?á‹”)
 ("ee2" ?á‹”)
 ("I2" ?á‹•)
 ("o2" ?á‹–)
 ("O2" ?á‹–)

 ; ("ee" ?á‹) ; old style
 ("ae" ?á‹)   ; new style
 ("aaa" ?á‹)  ; new style
 ("uu" ?á‹‘)
 ("UU" ?á‹‘)
 ("ii" ?á‹’)
 ("aa" ?á‹“)
 ("AA" ?á‹“)
 ("EE" ?á‹”)
 ("II" ?á‹•)
 ("ee" ?á‹•)   ; new style
 ("oo" ?á‹–)
 ("OO" ?á‹–)

 ("ze" ?á‹˜)
 ("zu" ?á‹™)
 ("zi" ?á‹š)
 ("za" ?á‹›)
 ("zE" ?á‹œ)
 ("zee" ?á‹œ)
 ("z" ?á‹)
 ("zo" ?á‹ž)
 ("zW" ?á‹Ÿ)
 ("zWa" ?á‹Ÿ)
 ("zWe" ["á‹ö ‡…"])
 ("zWu" ["á‹ö ‡‰"])
 ("zWi" ["á‹ö ‡†"])
 ("zWE" ["á‹ö ‡ˆ"])
 ("zWee" ["á‹ö ‡ˆ"])
 ("zW'" ["á‹ö ‡‰"])

 ("Ze" ?á‹ )
 ("Zu" ?á‹¡)
 ("Zi" ?á‹¢)
 ("Za" ?á‹£)
 ("ZE" ?á‹¤)
 ("Zee" ?á‹¤)
 ("Z" ?á‹¥)
 ("Zo" ?á‹¦)
 ("ZW" ?á‹§)
 ("ZWa" ?á‹§)
 ("ZWe" ["á‹¥ö ‡…"])
 ("ZWu" ["á‹¥ö ‡‰"])
 ("ZWi" ["á‹¥ö ‡†"])
 ("ZWE" ["á‹¥ö ‡ˆ"])
 ("ZWee" ["á‹¥ö ‡ˆ"])
 ("ZW'" ["á‹¥ö ‡‰"])

 ("ye" ?á‹¨)
 ("yu" ?á‹©)
 ("yi" ?á‹ª)
 ("ya" ?á‹«)
 ("yE" ?á‹¬)
 ("yee" ?á‹¬)
 ("y" ?á‹­)
 ("yo" ?á‹®)
 ("yW" ?ö ƒ¯)
 ("yWa" ?ö ƒ¯)
 ("yWe" ["á‹­ö ‡…"])
 ("yWu" ["á‹­ö ‡‰"])
 ("yWi" ["á‹­ö ‡†"])
 ("yWE" ["á‹­ö ‡ˆ"])
 ("yWee" ["á‹­ö ‡ˆ"])
 ("yW'" ["á‹­ö ‡‰"])

 ("Ye" ?á‹¨)
 ("Yu" ?á‹©)
 ("Yi" ?á‹ª)
 ("Ya" ?á‹«)
 ("YE" ?á‹¬)
 ("Yee" ?á‹¬)
 ("Y" ?á‹­)
 ("Yo" ?á‹®)
 ("YW" ?ö ƒ¯)
 ("YWa" ?ö ƒ¯)
 ("YWe" ["á‹­ö ‡…"])
 ("YWu" ["á‹­ö ‡‰"])
 ("YWi" ["á‹­ö ‡†"])
 ("YWE" ["á‹­ö ‡ˆ"])
 ("YWee" ["á‹­ö ‡ˆ"])
 ("YW'" ["á‹­ö ‡‰"])

 ("de" ?á‹°)
 ("du" ?á‹±)
 ("di" ?á‹²)
 ("da" ?á‹³)
 ("dE" ?á‹´)
 ("dee" ?á‹´)
 ("d" ?á‹µ)
 ("do" ?á‹¶)
 ("dW" ?á‹·)
 ("dWa" ?á‹·)
 ("dWe" ["á‹µö ‡…"])
 ("dWu" ["á‹µö ‡‰"])
 ("dWi" ["á‹µö ‡†"])
 ("dWE" ["á‹µö ‡ˆ"])
 ("dWee" ["á‹µö ‡ˆ"])
 ("dW'" ["á‹µö ‡‰"])

 ("De" ?á‹¸)
 ("Du" ?á‹¹)
 ("Di" ?á‹º)
 ("Da" ?á‹»)
 ("DE" ?á‹¼)
 ("Dee" ?á‹¼)
 ("D" ?á‹½)
 ("Do" ?á‹¾)
 ("DW" ?á‹¿)
 ("DWa" ?á‹¿)
 ("DWe" ["á‹½ö ‡…"])
 ("DWu" ["á‹½ö ‡‰"])
 ("DWi" ["á‹½ö ‡†"])
 ("DWE" ["á‹½ö ‡ˆ"])
 ("DWee" ["á‹½ö ‡ˆ"])
 ("DW'" ["á‹½ö ‡‰"])

 ("je" ?áŒ€)
 ("ju" ?áŒ)
 ("ji" ?áŒ‚)
 ("ja" ?áŒƒ)
 ("jE" ?áŒ„)
 ("jee" ?áŒ„)
 ("j" ?áŒ…)
 ("jo" ?áŒ†)
 ("jW" ?áŒ‡)
 ("jWa" ?áŒ‡)
 ("jWe" ["áŒ…ö ‡…"])
 ("jWu" ["áŒ…ö ‡‰"])
 ("jWi" ["áŒ…ö ‡†"])
 ("jWE" ["áŒ…ö ‡ˆ"])
 ("jWee" ["áŒ…ö ‡ˆ"])
 ("jW'" ["áŒ…ö ‡‰"])

 ("Je" ?áŒ€)
 ("Ju" ?áŒ)
 ("Ji" ?áŒ‚)
 ("Ja" ?áŒƒ)
 ("JE" ?áŒ„)
 ("Jee" ?áŒ„)
 ("J" ?áŒ…)
 ("Jo" ?áŒ†)
 ("JW" ?áŒ‡)
 ("JWa" ?áŒ‡)
 ("JWe" ["áŒ…ö ‡…"])
 ("JWu" ["áŒ…ö ‡‰"])
 ("JWi" ["áŒ…ö ‡†"])
 ("JWE" ["áŒ…ö ‡ˆ"])
 ("JWee" ["áŒ…ö ‡ˆ"])
 ("JW'" ["áŒ…ö ‡‰"])

 ("ge" ?áŒˆ)
 ("gu" ?áŒ‰)
 ("gi" ?áŒŠ)
 ("ga" ?áŒ‹)
 ("gE" ?áŒŒ)
 ("gee" ?áŒŒ)
 ("g" ?áŒ)
 ("go" ?áŒŽ)
 ("gWe" ?áŒ)
 ("gWu" ?áŒ•)
 ("gWi" ?áŒ’)
 ("gW" ?áŒ“)
 ("gWa" ?áŒ“)
 ("gWE" ?áŒ”)
 ("gWee" ?áŒ”)
 ("gW'" ?áŒ•)

 ("`ge" ?ö †°)
 ("`gu" ?ö †±)
 ("`gi" ?ö †²)
 ("`ga" ?ö †³)
 ("`gE" ?ö †´)
 ("`gee" ?ö †´)
 ("`g" ?ö †µ)
 ("`go" ?ö †¶)

 ("g2e" ?ö †°)
 ("g2u" ?ö †±)
 ("g2i" ?ö †²)
 ("g2a" ?ö †³)
 ("g2E" ?ö †´)
 ("g2ee" ?ö †´)
 ("g2" ?ö †µ)
 ("g2o" ?ö †¶)

 ("gge" ?ö †°)
 ("ggu" ?ö †±)
 ("ggi" ?ö †²)
 ("gga" ?ö †³)
 ("ggE" ?ö †´)
 ("ggee" ?ö †´)
 ("gg" ?ö †µ)
 ("ggo" ?ö †¶)

 ("Ge" ?áŒ˜)
 ("Gu" ?áŒ™)
 ("Gi" ?áŒš)
 ("Ga" ?áŒ›)
 ("GE" ?áŒœ)
 ("Gee" ?áŒœ)
 ("G" ?áŒ)
 ("Go" ?áŒž)
 ("GWe" ?ö †Š)
 ("GWu" ?ö †º)
 ("GWi" ?ö †š)
 ("GW" ?ö „Ÿ)
 ("GWa" ?ö „Ÿ)
 ("GWE" ?ö †ª)
 ("GWee" ?ö †ª)
 ("GW'" ?ö †º)

 ("Te" ?áŒ )
 ("Tu" ?áŒ¡)
 ("Ti" ?áŒ¢)
 ("Ta" ?áŒ£)
 ("TE" ?áŒ¤)
 ("Tee" ?áŒ¤)
 ("T" ?áŒ¥)
 ("To" ?áŒ¦)
 ("TW" ?áŒ§)
 ("TWa" ?áŒ§)
 ("TWe" ["áŒ¥ö ‡…"])
 ("TWu" ["áŒ¥ö ‡‰"])
 ("TWi" ["áŒ¥ö ‡†"])
 ("TWE" ["áŒ¥ö ‡ˆ"])
 ("TWee" ["áŒ¥ö ‡ˆ"])
 ("TW'" ["áŒ¥ö ‡‰"])

 ("Ce" ?áŒ¨)
 ("Cu" ?áŒ©)
 ("Ci" ?áŒª)
 ("Ca" ?áŒ«)
 ("CE" ?áŒ¬)
 ("Cee" ?áŒ¬)
 ("C" ?áŒ­)
 ("Co" ?áŒ®)
 ("CW" ?áŒ¯)
 ("CWa" ?áŒ¯)
 ("CWe" ["áŒ­ö ‡…"])
 ("CWu" ["áŒ­ö ‡‰"])
 ("CWi" ["áŒ­ö ‡†"])
 ("CWE" ["áŒ­ö ‡ˆ"])
 ("CWee" ["áŒ­ö ‡ˆ"])
 ("CW'" ["áŒ­ö ‡‰"])

 ("Pe" ?áŒ°)
 ("Pu" ?áŒ±)
 ("Pi" ?áŒ²)
 ("Pa" ?áŒ³)
 ("PE" ?áŒ´)
 ("Pee" ?áŒ´)
 ("P" ?áŒµ)
 ("Po" ?áŒ¶)
 ("PW" ?áŒ·)
 ("PWa" ?áŒ·)
 ("PWe" ["áŒµö ‡…"])
 ("PWu" ["áŒµö ‡‰"])
 ("PWi" ["áŒµö ‡†"])
 ("PWE" ["áŒµö ‡ˆ"])
 ("PWee" ["áŒµö ‡ˆ"])
 ("PW'" ["áŒµö ‡‰"])

 ("Se" ?áŒ¸)
 ("Su" ?áŒ¹)
 ("Si" ?áŒº)
 ("Sa" ?áŒ»)
 ("SE" ?áŒ¼)
 ("See" ?áŒ¼)
 ("S" ?áŒ½)
 ("So" ?áŒ¾)
 ("SW" ?áŒ¿)
 ("SWa" ?áŒ¿)
 ("SWe" ["áŒ½ö ‡…"])
 ("SWu" ["áŒ½ö ‡‰"])
 ("SWi" ["áŒ½ö ‡†"])
 ("SWE" ["áŒ½ö ‡ˆ"])
 ("SWee" ["áŒ½ö ‡ˆ"])
 ("SW'" ["áŒ½ö ‡‰"])

 ("`Se" ?á€)
 ("`Su" ?á)
 ("`Si" ?á‚)
 ("`Sa" ?áƒ)
 ("`SE" ?á„)
 ("`See" ?á„)
 ("`S" ?á…)
 ("`So" ?á†)
 ("`SW" ?áŒ¿)
 ("`SWa" ?áŒ¿)
 ("`SWe" ["á…ö ‡…"])
 ("`SWu" ["á…ö ‡‰"])
 ("`SWi" ["á…ö ‡†"])
 ("`SWE" ["á…ö ‡ˆ"])
 ("`SWee" ["á…ö ‡ˆ"])
 ("`SW'" ["á…ö ‡‰"])

 ("S2e" ?á€)
 ("S2u" ?á)
 ("S2i" ?á‚)
 ("S2a" ?áƒ)
 ("S2E" ?á„)
 ("S2ee" ?á„)
 ("S2" ?á…)
 ("S2o" ?á†)
 ("S2W" ?áŒ¿)
 ("S2Wa" ?áŒ¿)
 ("S2We" ["á…ö ‡…"])
 ("S2Wu" ["á…ö ‡‰"])
 ("S2Wi" ["á…ö ‡†"])
 ("S2WE" ["á…ö ‡ˆ"])
 ("S2Wee" ["á…ö ‡ˆ"])
 ("S2W'" ["á…ö ‡‰"])

 ("SSe" ?á€)
 ("SSu" ?á)
 ("SSi" ?á‚)
 ("SSa" ?áƒ)
 ("SSE" ?á„)
 ("SSee" ?á„)
 ("SS" ?á…)
 ("SSo" ?á†)
 ("SSW" ?áŒ¿)
 ("SSWa" ?áŒ¿)
 ("SSWe" ["á…ö ‡…"])
 ("SSWu" ["á…ö ‡‰"])
 ("SSWi" ["á…ö ‡†"])
 ("SSWE" ["á…ö ‡ˆ"])
 ("SSWee" ["á…ö ‡ˆ"])
 ("SW'" ["á…ö ‡‰"])

 ("fe" ?áˆ)
 ("fu" ?á‰)
 ("fi" ?áŠ)
 ("fa" ?á‹)
 ("fE" ?áŒ)
 ("fee" ?áŒ)
 ("f" ?á)
 ("fo" ?áŽ)
 ("fWe" ?ö †‹)
 ("fWu" ?ö †»)
 ("fWi" ?ö †›)
 ("fW" ?á)
 ("fWa" ?á)
 ("fWE" ?ö †«)
 ("fWee" ?ö †«)
 ("fW'" ?ö †»)
 ("fY" ?áš)
 ("fYa" ?áš)

 ("Fe" ?áˆ)
 ("Fu" ?á‰)
 ("Fi" ?áŠ)
 ("Fa" ?á‹)
 ("FE" ?áŒ)
 ("Fee" ?áŒ)
 ("F" ?á)
 ("Fo" ?áŽ)
 ("FWe" ?ö †‹)
 ("FWu" ?ö †»)
 ("FWi" ?ö †›)
 ("FW" ?á)
 ("FWa" ?á)
 ("FWE" ?ö †«)
 ("FWee" ?ö †«)
 ("FW'" ?ö †»)
 ("FY" ?áš)
 ("FYa" ?áš)

 ("pe" ?á)
 ("pu" ?á‘)
 ("pi" ?á’)
 ("pa" ?á“)
 ("pE" ?á”)
 ("pee" ?á”)
 ("p" ?á•)
 ("po" ?á–)
 ("pWe" ?ö †Œ)
 ("pWu" ?ö †¼)
 ("pWi" ?ö †œ)
 ("pW" ?á—)
 ("pWa" ?á—)
 ("pWE" ?ö †¬)
 ("pWee" ?ö †¬)
 ("pW'" ?ö †¼)

 ("'" [""])
 ("''" ?')
 (":" ?á¡)
 ("::" ?á¢)
 (":::" ?:)
 ("." ?á¢)
 (".." ?ö ‡Œ)
 ("..." ?.)
 ("," ?á£)
 (",," ?,)
 (";" ?á¤)
 (";;" ?\;)
 ("-:" ?á¥)
 (":-" ?á¦)
 ("*" ?*)
 ("**" ?á¨)
 (":|:" ?á¨)
 ("?" ?ö ‡)
 ("??" ?á§)
 ("`?" ?á§)
 ("???" ??)
 ("<<" ?ö ‡)
 (">>" ?ö ‡Ž)
 ("`!" ?ö ‡‹)
 ("wWe" ?ö ‡…)
 ("wWu" ?ö ‡‰)
 ("wWi" ?ö ‡†)
 ("wW" ?ö ‡‡)
 ("wWa" ?ö ‡‡)
 ("wWE" ?ö ‡ˆ)
 ("wWee" ?ö ‡ˆ)
 ("wW'" ?ö ‡‰)
 ("We" ?ö ‡…)
 ("Wu" ?ö ‡‰)
 ("Wi" ?ö ‡†)
 ("W" ?ö ‡‡)
 ("Wa" ?ö ‡‡)
 ("WE" ?ö ‡ˆ)
 ("Wee" ?ö ‡ˆ)
 ("W'" ?ö ‡‰)
 ("`1" ?á©)
 ("`2" ?áª)
 ("`3" ?á«)
 ("`4" ?á¬)
 ("`5" ?á­)
 ("`6" ?á®)
 ("`7" ?á¯)
 ("`8" ?á°)
 ("`9" ?á±)
 ("`10" ?á²)
 ("`20" ?á³)
 ("`30" ?á´)
 ("`40" ?áµ)
 ("`50" ?á¶)
 ("`60" ?á·)
 ("`70" ?á¸)
 ("`80" ?á¹)
 ("`90" ?áº)
 ("`100" ?á»)
 ("`1000" ["á²á»"])
 ("`2000" ["á³á»"])
 ("`3000" ["á´á»"])
 ("`4000" ["áµá»"])
 ("`5000" ["á¶á»"])
 ("`6000" ["á·á»"])
 ("`7000" ["á¸á»"])
 ("`8000" ["á¹á»"])
 ("`9000" ["áºá»"])
 ("`10000" ?á¼)
 ("`20000" ["áªá¼"])
 ("`30000" ["á«á¼"])
 ("`40000" ["á¬á¼"])
 ("`50000" ["á­á¼"])
 ("`60000" ["á®á¼"])
 ("`70000" ["á¯á¼"])
 ("`80000" ["á°á¼"])
 ("`90000" ["á±á¼"])
 ("`100000" ["á²á¼"])
 ("`200000" ["á³á¼"])
 ("`300000" ["á´á¼"])
 ("`400000" ["áµá¼"])
 ("`500000" ["á¶á¼"])
 ("`600000" ["á·á¼"])
 ("`700000" ["á¸á¼"])
 ("`800000" ["á¹á¼"])
 ("`900000" ["áºá¼"])
 ("`1000000" ["á»á¼"])
)

(defun ethio-select-a-translation ()
  ;; The translation of `a' depends on the language
  ;; (either Tigrigna or Amharic).
  (quail-defrule "a"
		 (if (ethio-prefer-amharic-p) ?áŠ  ?áŠ£)
		 "ethiopic"))

;;; ethiopic.el ends here
