;;; data-tests.el --- Tests for data.rs

;;; Code:

(require 'ert)

(ert-deftest data-test--aref-base ()
  "Verify (aref) base cases"
  (should-error (aref "abc" -1) :type 'args-out-of-range)
  (should (eq (aref "abcdef" 3)
              ?d))
  (should-error (aref "abc" 3)
                :type 'args-out-of-range)
  (should (eq (aref (bool-vector t nil t nil) 1)
              nil))
  (should-error (aref (bool-vector t nil t nil) 4)
                :type 'args-out-of-range)
  (let ((tbl (make-char-table 'foo 0)))
    (should (eq (aref tbl 0)
                0)))
  (let* ((x 1)
         (y 2)
         (z 3)
         (v [x y z]))
    (should (eq (aref v 1)
                'y))
    (should-error (aref v 5)
                  :type 'args-out-of-range))
  (should (eq (aref (kbd "<f1> SPC") 1)
              32))
  (let ((r (make-record 'foo 9 'Z)))
    (should (eq (aref r 1)
                'Z))
    (should-error (aref r 10)
                  :type 'args-out-of-range))
  (should-error (aref 100 1)
                :type 'wrong-type-argument))

(ert-deftest data-test--aset-base ()
  "Verify (aset) base cases"
  (should-error (aset "abc" -1 ?d) :type 'args-out-of-range)
  (should-error (aset 100 1 1)
                :type 'wrong-type-argument)
  (let ((object "abcdef"))
    (should (eq (aset object 3 ?w)
                ?w))
    (should (eq (aref object 3)
                ?w)))
  (should-error (aset "abc" 3 ?w)
                :type 'args-out-of-range)
  (let ((bv (bool-vector t nil t nil)))
    (should-error (aset bv 4 t)
                  :type 'args-out-of-range)
    (should (eq (aset bv 1 t)
                t))
    (should (eq (aref bv 1)
                t)))
  (let ((tbl (make-char-table 'foo 0)))
    (should (eq (aset tbl 0 1)
                1))
    (should (eq (aref tbl 0)
                1)))
  (let* ((x 1)
         (y 2)
         (z 3)
         (a 10)
         (v [x y z]))
    (should-error (aset v 5 a)
                  :type 'args-out-of-range)
    (should (eq (aset v 1 a)
                10))
    (should (eq (aref v 1)
                10)))
  (let ((object (kbd "<f1> SPC")))
    (should (eq (aset object 1 33)
                33))
    (should (eq (aref object 1)
                33)))
  (let ((r (make-record 'foo 9 'Z)))
    (should-error (aref r 10)
                  :type 'args-out-of-range)
    (should (eq (aset r 1 'A)
                'A))
    (should (eq (aref r 1)
                'A)))
  )

(provide 'data-tests)
;;; data-tests.el ends here
