#  Hacked up Nmake makefile for GNU Emacs
#   Geoff Voelker (voelker@cs.washington.edu)
#  Copyright (c) 1994 Free Software Foundation, Inc.
#
#  This file is part of GNU Emacs.
#  
#  GNU Emacs is free software; you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation; either version 2, or (at your option)
#  any later version.
#  
#  GNU Emacs is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#  
#  You should have received a copy of the GNU General Public License
#  along with GNU Emacs; see the file COPYING.  If not, write to the
#  Free Software Foundation, Inc., 59 Temple Place - Suite 330,
#  Boston, MA 02111-1307, USA.
#

!include ..\nt\makefile.def

all:

topdontcompile = cus-load.el forms-d2.el forms-pass.el patcomp.el \
		 subdirs.el version.el
maildontcompile = mail\blessmail.el mail\sc.el
playdontcompile = play\bruce.el
interdontcompile = international\latin-1.el international\latin-2.el \
		 international\latin-3.el international\latin-4.el \
		 international\latin-5.el international\mule-conf.el

#
# Assuming INSTALL_DIR is defined, copy the elisp files to it
# Windows 95 makes this harder than it should be.
#
install:;	- mkdir $(INSTALL_DIR)\lisp
		- $(DEL) .\same-dir.tst
		- $(DEL) $(INSTALL_DIR)\lisp\same-dir.tst
		echo SameDirTest > $(INSTALL_DIR)\lisp\same-dir.tst
!ifdef COPY_LISP_SOURCE
		if not exist .\same-dir.tst $(CP_DIR) . $(INSTALL_DIR)\lisp
!else
		if not exist .\same-dir.tst $(CP_DIR) *.elc $(INSTALL_DIR)\lisp
		if not exist .\same-dir.tst $(CP) cus-load.el $(INSTALL_DIR)\lisp
		if not exist .\same-dir.tst $(CP) forms*.el $(INSTALL_DIR)\lisp
		if not exist .\same-dir.tst $(CP) patcomp.el $(INSTALL_DIR)\lisp
		if not exist .\same-dir.tst $(CP) subdirs.el $(INSTALL_DIR)\lisp
		if not exist .\same-dir.tst $(CP) version.el $(INSTALL_DIR)\lisp
		if not exist .\same-dir.tst $(CP) mail\blessmail.el $(INSTALL_DIR)\lisp\mail
		if not exist .\same-dir.tst $(CP) mail\sc.el $(INSTALL_DIR)\lisp\mail
		if not exist .\same-dir.tst $(CP) play\bruce.el $(INSTALL_DIR)\lisp\play
		if not exist .\same-dir.tst $(CP) international\latin-*.el $(INSTALL_DIR)\lisp\international
		if not exist .\same-dir.tst $(CP) international\mule-conf.el $(INSTALL_DIR)\lisp\international
		- $(DEL) $(INSTALL_DIR)\lisp\same-dir.tst
!endif

#
# Maintenance
# 
clean:;		- $(DEL) *~ term\*~
		- $(DEL) *.orig *.rej *.crlf
		- $(DEL) emacs-lisp\*.orig emacs-lisp\*.rej emacs-lisp\*.crlf
		- $(DEL) emulation\*.orig emulation\*.rej emulation\*.crlf
		- $(DEL) gnus\*.orig gnus\*.rej gnus\*.crlf
		- $(DEL) international\*.orig international\*.rej international\*.crlf
		- $(DEL) language\*.orig language\*.rej language\*.crlf
		- $(DEL) mail\*.orig mail\*.rej mail\*.crlf
		- $(DEL) play\*.orig play\*.rej play\*.crlf
		- $(DEL) progmodes\*.orig progmodes\*.rej progmodes\*.crlf
		- $(DEL) term\*.orig term\*.rej term\*.crlf
		- $(DEL) textmodes\*.orig textmodes\*.rej textmodes\*.crlf
		- $(DEL_TREE) deleted
