#!/bin/sh

# Convert git log output to ChangeLog format for GNU Emacs.

# Copyright (C) 2014-2015 Free Software Foundation, Inc.

# Author: Paul Eggert

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

LC_ALL=C
export LC_ALL

# The newest revision that should not appear in the generated ChangeLog.
gen_origin=2c1b8604946efbcd8ec5dd6c6dda7541ce4fc3c0
test -n "$1" && test "$1" != "." && gen_origin=$1

output=$2
test -n "$output" || output=ChangeLog

# If this is not a Git repository, just generate an empty ChangeLog.
test -d ${srcprefix}.git || {
  # Remove any old ChangeLog, in case it is a vc-dwim symlink.
  rm -f "${distprefix}$output" || exit
  >"${distprefix}$output"
  exit
}

# Use Gnulib's packaged ChangeLog generator.
${srcprefix}build-aux/gitlog-to-changelog --ignore-matching='^; ' \
  --format='%B' \
  "$gen_origin.." >"${distprefix}ChangeLog.tmp" || exit

if test -s "${distprefix}ChangeLog.tmp"; then

  # Fix up bug references.
  # This would be better as eg a --transform option to gitlog-to-changelog,
  # but... effort.  FIXME does not handle rare cases like:
  # Fixes: debbugs:19434 debbugs:19519
  sed 's/	Fixes: \(debbugs:\|bug#\)\([0-9][0-9]*\)/	(Bug#\2)/' \
      "${distprefix}ChangeLog.tmp" > "${distprefix}ChangeLog.tmp2"
  mv "${distprefix}ChangeLog.tmp2" "${distprefix}ChangeLog.tmp"

  # Find the years covered by the generated ChangeLog, so that
  # a proper copyright notice can be output.
  years=`
    sed -n 's/^\([0-9][0-9]*\).*/\1/p' "${distprefix}ChangeLog.tmp" |
    sort -nu
  `
  start_year=
  end_year=
  for year in $years; do
    : ${start_year:=$year}
    end_year=$year
  done

  if test "$start_year" = "$end_year"; then
    year_range=$start_year
  else
    year_range=$start_year-$end_year
  fi

  # Append a proper copyright notice.
  sed -n '
    1i\

    /^;; Local Variables:/,${
       s/\(Copyright[ (C)]*\)[0-9]*-[0-9]*/\1'"$year_range"'/
       p
    }
  ' <ChangeLog.2 >>"${distprefix}ChangeLog.tmp" || exit
fi

# Install the generated ChangeLog.
test "$output" = "ChangeLog.tmp" || \
  mv -i "${distprefix}ChangeLog.tmp" "${distprefix}$output"
