.\" See section COPYING for copyright and redistribution information.
.TH b2m 1
.SH NAME
b2m \- convert RMAIL Babyl format to Unix mailbox format
.SH SYNOPSIS
.B b2m
.SH DESCRIPTION
.B b2m
accepts Babyl format (as used by
.BR RMAIL
in
.BR "GNU Emacs" )
mail on standard input, and converts it to Unix mail format on
standard output.  This program is distributed with
.BR "GNU Emacs" .
.PP
.SH OPTIONS
The program accepts unambiguous abbreviations for long option names.
.TP
.B \-V, \-\-version
Display version information.
.TP
.B \-h, \-\-help
Display basic usage information.
.
.SH SEE ALSO
The Babyl format is described in the file
.B etc/BABYL
in the Emacs distribution.
.B RMAIL
is documented in the GNU Emacs manual, which  you  can  read  using
.BR Info ,
either from Emacs or as a standalone program.
.
.SH AUTHORS
.I b2m
was originally written by Ed Wilkinson.  Francesco Potorti updated it
according to the GNU coding standards.
.SH COPYING
Copyright 
.if t \(co
.if n (C)
2008 Free Software Foundation, Inc.
.PP
Permission is granted to make and distribute verbatim copies of this
document provided the copyright notice and this permission notice are
preserved on all copies.
.PP
Permission is granted to copy and distribute modified versions of
this document under the conditions for verbatim copying, provided that
the entire resulting derived work is distributed under the terms of
a permission notice identical to this one.
.PP
Permission is granted to copy and distribute translations of this
document into another language, under the above conditions for
modified versions, except that this permission notice may be stated
in a translation approved by the Free Software Foundation.
.
.\" arch-tag: 7586e605-c400-447e-82ff-4d38e3c0a37d
