#! /usr/bin/perl

# Copyright (C) 2001 Free Software Foundation, Inc.
#
# This file is part of GNU Emacs.
#
# GNU Emacs is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2, or (at your option)
# any later version.
#
# GNU Emacs is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with GNU Emacs; see the file COPYING.  If not, write to the
# Free Software Foundation, Inc., 59 Temple Place - Suite 330,
# Boston, MA 02111-1307, USA.

# Build Emacs in several different configurations.

@configs =
  (
   ["--without-x", 		  "--optim"],
   ["--without-x-toolkit", 	  "--optim"],
   ["--without-toolkit-scroll-bars", "--optim"],
   ["--with-x-toolkit=lucid", 	  "--optim"],
   ["--with-x-toolkit=motif", 	  "--optim"],
   ["--with-x-toolkit=motif", 	  "--enable-checking"],
   ["--with-x-toolkit=motif", 	  "--gcc3"],
   ["--with-x-toolkit=motif", 	  ""],
  );

$log = "/tmp/$$.out";
print "Using log file $log\n";
unlink $log;

$root = $ENV{"EMACS_ROOT"};
$root = "/gd/gnu/emacs" unless $root;
chdir ($root) or die "Cannot chdir to emacs";

foreach $config (@configs)
  {
    my $configure_options = @$config[0];
    my $make_options = @$config[1];
    my $rc;

    print "$configure_options, $make_options\n";
    unlink "config.cache";

    $rc = system ("$root/configure $configure_options >>$log 2>&1");
    if ($rc != 0) 
      {
	print "configure failed\n";
	exit 1;
      }

    $rc = system ("make-emacs --all $make_options >>$log 2>&1");
    if ($rc != 0) 
      {
	print "Make failed\n";
	exit 1;
      }
  }

# Local Variables:
# mode: cperl
# End:
