@c -*-texinfo-*-
@c This is part of the GNU Emacs Lisp Reference Manual.
@c Copyright (C) 1990, 1991, 1992, 1993 Free Software Foundation, Inc. 
@c See the file elisp.texi for copying conditions.
@setfilename ../info/locals
@node Standard Buffer-Local Variables, Standard Keymaps, Standard Errors, Top
@appendix Buffer-Local Variables
@c The title "Standard Buffer-Local Variables" is too long for
@c smallbook. --rjc 30mar92

  The table below lists the general-purpose Emacs variables that are
automatically local (when set) in each buffer.  Many Lisp packages
define such variables for their internal use; we don't list them here.

@table @code
@item abbrev-mode
@pxref{Abbrevs}

@item auto-fill-function
@pxref{Auto Filling}

@item buffer-auto-save-file-name
@pxref{Auto-Saving}

@item buffer-backed-up
@pxref{Backup Files}

@item buffer-display-table
@pxref{Display Tables}

@item buffer-file-format
@pxref{Format Conversion}

@item buffer-file-name
@pxref{Buffer File Name}

@item buffer-file-number
@pxref{Buffer File Name}

@item buffer-file-truename
@pxref{Buffer File Name}

@item buffer-file-type
@pxref{Files and MS-DOS}

@item buffer-invisibility-spec
@pxref{Invisible Text}

@item buffer-offer-save
@pxref{Saving Buffers}

@item buffer-read-only
@pxref{Read Only Buffers}

@item buffer-saved-size
@pxref{Point}

@item buffer-undo-list
@pxref{Undo}

@item cache-long-line-scans
@pxref{Text Lines}

@item case-fold-search
@pxref{Searching and Case}

@item ctl-arrow
@pxref{Usual Display}

@item comment-column
@pxref{Comments,,, emacs, The GNU Emacs Manual}

@item default-directory
@pxref{System Environment}

@item defun-prompt-regexp
@pxref{List Motion}

@item fill-column
@pxref{Auto Filling}

@item goal-column
@pxref{Moving Point,,, emacs, The GNU Emacs Manual}

@item left-margin
@pxref{Indentation}

@item local-abbrev-table
@pxref{Abbrevs}

@item local-write-file-hooks
@pxref{Saving Buffers}

@item major-mode
@pxref{Mode Help}

@item mark-active
@pxref{The Mark}

@item mark-ring
@pxref{The Mark}

@item minor-modes
@pxref{Minor Modes}

@item mode-line-buffer-identification
@pxref{Mode Line Variables}

@item mode-line-format
@pxref{Mode Line Data}

@item mode-line-modified
@pxref{Mode Line Variables}

@item mode-line-process
@pxref{Mode Line Variables}

@item mode-name
@pxref{Mode Line Variables}

@item overwrite-mode
@pxref{Insertion}

@item paragraph-separate
@pxref{Standard Regexps}

@item paragraph-start
@pxref{Standard Regexps}

@item point-before-scroll
Used for communication between mouse commands and scroll-bar commands.

@item require-final-newline
@pxref{Insertion}

@item selective-display
@pxref{Selective Display}

@item selective-display-ellipses
@pxref{Selective Display}

@item tab-width
@pxref{Usual Display}

@item truncate-lines
@pxref{Truncation}

@item vc-mode
@pxref{Mode Line Variables}
@end table
