@c -*-texinfo-*-
@c This is part of the GNU Emacs Lisp Reference Manual.
@c Copyright (C) 1990, 1991, 1992, 1993 Free Software Foundation, Inc. 
@c See the file elisp.texi for copying conditions.
@setfilename ../info/maps
@node Standard Keymaps, Standard Hooks, Standard Buffer-Local Variables, Top
@appendix Standard Keymaps

The following symbols are used as the names for various keymaps.
Some of these exist when Emacs is first started, others are
loaded only when their respective mode is used.  This is not
an exhaustive list.

Almost all of these maps are used as local maps.  Indeed, of the modes
that presently exist, only Vip mode and Terminal mode ever change the
global keymap.

@table @code
@item Buffer-menu-mode-map
@vindex Buffer-menu-mode-map
A full keymap used by Buffer Menu mode.

@item c-mode-map
@vindex c-mode-map
A sparse keymap used by C mode.

@item command-history-map
@vindex command-history-map
A full keymap used by Command History mode.

@item ctl-x-4-map
@vindex ctl-x-4-map
A sparse keymap for subcommands of the prefix @kbd{C-x 4}.

@item ctl-x-5-map
@vindex ctl-x-5-map
A sparse keymap for subcommands of the prefix @kbd{C-x 5}.

@item ctl-x-map
@vindex ctl-x-map
A full keymap for @kbd{C-x} commands.

@item debugger-mode-map
@vindex debugger-mode-map
A full keymap used by Debugger mode.

@item dired-mode-map
@vindex dired-mode-map
A full keymap for @code{dired-mode} buffers.

@item edit-abbrevs-map
@vindex edit-abbrevs-map
A sparse keymap used in @code{edit-abbrevs}.

@item edit-tab-stops-map
@vindex edit-tab-stops-map
A sparse keymap used in @code{edit-tab-stops}.

@item electric-buffer-menu-mode-map
@vindex electric-buffer-menu-mode-map
A full keymap used by Electric Buffer Menu mode.

@item electric-history-map
@vindex electric-history-map
A full keymap used by Electric Command History mode.

@item emacs-lisp-mode-map
@vindex emacs-lisp-mode-map
A sparse keymap used by Emacs Lisp mode.

@item facemenu-menu
@vindex facemenu-menu
The keymap that displays the Text Properties menu.

@item facemenu-background-menu
@vindex facemenu-background-menu
The keymap that displays the Background Color submenu of the Text
Properties menu.

@item facemenu-face-menu
@vindex facemenu-face-menu
The keymap that displays the Face submenu of the Text Properties menu.

@item facemenu-foreground-menu
@vindex facemenu-foreground-menu
The keymap that displays the Foreground Color submenu of the Text
Properties menu.

@item facemenu-indentation-menu
@vindex facemenu-indentation-menu
The keymap that displays the Indentation submenu of the Text Properties menu.

@item facemenu-justification-menu
@vindex facemenu-justification-menu
The keymap that displays the Justification submenu of the Text
Properties menu.

@item facemenu-special-menu
@vindex facemenu-special-menu
The keymap that displays the Special Props submenu of the Text
Properties menu.

@item function-key-map
@vindex function-key-map
The keymap for translating keypad and function keys.@*
If there are none, then it contains an empty sparse keymap.

@item fundamental-mode-map
@vindex fundamental-mode-map
The local keymap for Fundamental mode.@*
It is empty and should not be changed.

@item Helper-help-map
@vindex Helper-help-map
A full keymap used by the help utility package.@*
It has the same keymap in its value cell and in its function
cell.

@item Info-edit-map
@vindex Info-edit-map
A sparse keymap used by the @kbd{e} command of Info.

@item Info-mode-map
@vindex Info-mode-map
A sparse keymap containing Info commands.

@item isearch-mode-map
@vindex isearch-mode-map
A keymap that defines the characters you can type within incremental
search.

@item key-translation-map
@vindex key-translation-map
A keymap for translating keys.  This one overrides ordinary key
bindings, unlike @code{function-key-map}.

@item lisp-interaction-mode-map
@vindex lisp-interaction-mode-map
A sparse keymap used by Lisp mode.

@item lisp-mode-map
@vindex lisp-mode-map
A sparse keymap used by Lisp mode.

@item menu-bar-edit-menu
@vindex menu-bar-edit-menu
The keymap which displays the Edit menu in the menu bar.

@item menu-bar-files-menu
@vindex menu-bar-files-menu
The keymap which displays the Files menu in the menu bar.

@item menu-bar-help-menu
@vindex menu-bar-help-menu
The keymap which displays the Help menu in the menu bar.

@item menu-bar-search-menu
@vindex menu-bar-search-menu
The keymap which displays the Search menu in the menu bar.

@item menu-bar-tools-menu
@vindex menu-bar-tools-menu
The keymap which displays the Tools menu in the menu bar.

@item mode-specific-map
@vindex mode-specific-map
The keymap for characters following @kbd{C-c}.  Note, this is in the
global map.  This map is not actually mode specific: its name was chosen
to be informative for the user in @kbd{C-h b} (@code{display-bindings}),
where it describes the main use of the @kbd{C-c} prefix key.

@item occur-mode-map
@vindex occur-mode-map
A local keymap used by Occur mode.

@item query-replace-map
@vindex query-replace-map
A local keymap used for responses in @code{query-replace} and related
commands; also for @code{y-or-n-p} and @code{map-y-or-n-p}.  The functions
that use this map do not support prefix keys; they look up one event at a
time.

@item text-mode-map
@vindex text-mode-map
A sparse keymap used by Text mode.

@item view-mode-map
@vindex view-mode-map
A full keymap used by View mode.
@end table
