@c This is part of the Emacs manual.
@c Copyright (C) 2005-2012 Free Software Foundation, Inc.
@c See file emacs.texi for copying conditions.

@node Antinews, Mac OS / GNUstep, X Resources, Top
@appendix Emacs 23 Antinews
@c Update the emacs.texi Antinews menu entry with the above version number.

  For those users who live backwards in time, here is information
about downgrading to Emacs version 23.4.  We hope you will enjoy the
greater simplicity that results from the absence of many Emacs
@value{EMACSVER} features.

@itemize @bullet
@item
FIXME

@item
To keep up with decreasing computer memory capacity and disk space, many
other functions and files have been eliminated in Emacs 23.4.
@end itemize
